{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "1868ffa29a72af25f93345f20e044b832b98cf11abaeab366f595f09223e4c6452a1259924304935a1ce74acf80298626bd76d4ba238cab1756e2f31ee1a6c4d",
          "sha256": "6fbbfe465dc202594105b61aa4a8c6b5ca496b7e3378bba73b6302e64bc69cdb",
          "sha1": "353c6f8934dbbac9348fabc8734e02332e5352d3",
          "md5": "b06504132d51e5e62a303d0ed73fbb82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "1868ffa29a72af25f93345f20e044b832b98cf11abaeab366f595f09223e4c6452a1259924304935a1ce74acf80298626bd76d4ba238cab1756e2f31ee1a6c4d",
          "sha256": "6fbbfe465dc202594105b61aa4a8c6b5ca496b7e3378bba73b6302e64bc69cdb",
          "sha1": "353c6f8934dbbac9348fabc8734e02332e5352d3",
          "md5": "b06504132d51e5e62a303d0ed73fbb82"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-javadoc.jar",
          "url": "app-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-sources.jar",
          "url": "app-1.0.0-sources.jar",
          "size": 3538,
          "sha512": "15dcec97f723ec62c0433d0ff92897d7975ab99fe0d847bcf22e43716bc88da4adca959c6b89573069eaa312864a998109cde764c681c25bf8455824239e2d9f",
          "sha256": "31d78d4e5b507dafc19cdba4bc7b1e5f533f9517e1e72d1c8acb62e4fcf10c0c",
          "sha1": "0b6ca0da3d10d8b0cfec6d0ef177ae9726a10cdf",
          "md5": "3d1096c9375e1e66995223ac8fa43c9c"
        }
      ]
    }
  ]
}
