{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "37025250a53e2f383cb88d3130e45b2a4d9bf74c98468df246b1232b4a2e23fac9f6f991e9839d2671a30df909ab3a008267b3660871626e49562650f60ebabe",
          "sha256": "32d704b2b8b93ae0fe1da648e7f4147cb290a6d09ed2dc5a54d8dbeaa9026422",
          "sha1": "ef25f67160a9d6967ac69334f8929a6ba8b23754",
          "md5": "1121c52d7a12058cef2aa566ef538742"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "37025250a53e2f383cb88d3130e45b2a4d9bf74c98468df246b1232b4a2e23fac9f6f991e9839d2671a30df909ab3a008267b3660871626e49562650f60ebabe",
          "sha256": "32d704b2b8b93ae0fe1da648e7f4147cb290a6d09ed2dc5a54d8dbeaa9026422",
          "sha1": "ef25f67160a9d6967ac69334f8929a6ba8b23754",
          "md5": "1121c52d7a12058cef2aa566ef538742"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-javadoc.jar",
          "url": "app-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "21c101500e34d48b1111680a1bbe8fd902850a9042aea9105dbf3687d6a3df5d42a82dd5c80ff19ea30376ab7a421526a8402f7516312914687198fe8a8f4a92",
          "sha256": "2ae96a813d38bb86b1ac8d250750c2c1200106c783a3132ea2550b9ec7e8234a",
          "sha1": "c20c2198a8d3fac8cd69b523b273fa2f74eb2f72",
          "md5": "14757d34b12fc4ce569b3029f0282f4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-sources.jar",
          "url": "app-1.0.0-sources.jar",
          "size": 3538,
          "sha512": "455a150392eaf047b69d4f2dcc4c50fa9c152c2c5bf8f740435ea9e0dfd4c18b4e5d8fad39ef6ac44891103912e63daafdb4eab3e0b6351585db013f09dd8d12",
          "sha256": "fc425d5f9ad31750356fe5e0233177125da338f3c98e17d9a8f211dec3e54efe",
          "sha1": "b3a71c0347021dda2526624c3037c8c1b4582cf5",
          "md5": "9959d4419363e6712d0986c72b0df6a7"
        }
      ]
    }
  ]
}
