{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3745,
          "sha512": "9d97714cc307411e50ec27abd11ee3b0907525da2780100f0740c4240e400bfe22d9f01e0ba15b38ec288794130fffbd1787eb0544abf686222bc058d62afe1d",
          "sha256": "91a82a6d565f64b2f14f01752f4337ab6de9396d6c6f2ee060030fb489a0b6e6",
          "sha1": "daf3e847f6993c1d2e141c91189d464a35fbfda5",
          "md5": "1634123b8745a2fadd8ac7fc52f56cb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3745,
          "sha512": "9d97714cc307411e50ec27abd11ee3b0907525da2780100f0740c4240e400bfe22d9f01e0ba15b38ec288794130fffbd1787eb0544abf686222bc058d62afe1d",
          "sha256": "91a82a6d565f64b2f14f01752f4337ab6de9396d6c6f2ee060030fb489a0b6e6",
          "sha1": "daf3e847f6993c1d2e141c91189d464a35fbfda5",
          "md5": "1634123b8745a2fadd8ac7fc52f56cb8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-javadoc.jar",
          "url": "app-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "4b85cfb1a65b9888d4e81ac027b1887175ed648a5d4d1eab663509c46a365c37c7eff24a076c7c36f23fc3467f9e7e5d9e9f7257cda619d1533b311a2f02f3d7",
          "sha256": "2cfd94429fd3f60eac3a4baf1e27d185fdcf274fc00101d7f7a3a5a869851e00",
          "sha1": "0f03b7d1d41957b6cdcfe09d88e38f7e7c18de66",
          "md5": "8faade3ee918bb281e04764847c8ef85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-sources.jar",
          "url": "app-1.0.0-sources.jar",
          "size": 3540,
          "sha512": "826612072004249094b53c4c6f81560fad4847493500f841bc1a1297a14ee9c27326a18abef9a91f9fb75858dd09795a731e742d8849f25baec9a0bcf12a5850",
          "sha256": "b57f2509c205946ddb15bb844da3dd2c1446a39da19622c6df4f1f28969f1590",
          "sha1": "a63ca6558d19615d210d4439cb8a5a4b44e48a48",
          "md5": "1eae9bb5355e9bf7484c74f3bcdb99f2"
        }
      ]
    }
  ]
}
