{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "d1389f73d071541820e36e62d4953f2a9aa356b81c001d5035000f384d0d6beabe675a4978d4deba8a7411f5139dfd449a2fa5a0af4fa294986ae8fd08a9f1c1",
          "sha256": "ecd6640b6ceddb41915ee5fd27b8144ed49a26a1f8155ff74d9a1feee8658183",
          "sha1": "a003c41ce5cf8d68db5778d1f5e6dceb23095c68",
          "md5": "7124cd6f44274eb790f6c4d51f1095dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "d1389f73d071541820e36e62d4953f2a9aa356b81c001d5035000f384d0d6beabe675a4978d4deba8a7411f5139dfd449a2fa5a0af4fa294986ae8fd08a9f1c1",
          "sha256": "ecd6640b6ceddb41915ee5fd27b8144ed49a26a1f8155ff74d9a1feee8658183",
          "sha1": "a003c41ce5cf8d68db5778d1f5e6dceb23095c68",
          "md5": "7124cd6f44274eb790f6c4d51f1095dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-javadoc.jar",
          "url": "jackson-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "de8855ba0efc3c297b881bd4ce028a8ba7b7188bfb148736910be453892e2ee878662a96319d43a94caeb67273058210db6c09079ff45da781918a0c347985bb",
          "sha256": "3d8bfdef1f136569f70e14a8b52760151d63cc1e763f7dd5abee6244546f9ca0",
          "sha1": "f9606eb4090119874b4f479d828a11486577187c",
          "md5": "1beb9734685dcbc065e7acc48945d366"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-sources.jar",
          "url": "jackson-1.0.1-beta-sources.jar",
          "size": 9847,
          "sha512": "a51b5caf05e3bd085f108d559b25d5f290f3620071bb04574d1e6747560b3ed03555ca1de5dd6871b1de55dc3352693c1ea13ef1508d37db646b16ce9fdff3bf",
          "sha256": "f89e31a2d0297aabf7a547e015e70a96d4b735a1d2b65d1aef0fa74877b927d0",
          "sha1": "3a7b8dad861726f77553a5daea8a167b25fd5ccb",
          "md5": "d3a3c0c433ff1b79b7c33b40878aa592"
        }
      ]
    }
  ]
}
