{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "4a4aaa6b1b775e04b3ae471b31be9a7c7eede7840467dd164fbe4912484f2700858d1e92f98b47ba6df4e754eed0fde96c0874049ed4db6dcef91341c6363a56",
          "sha256": "d14e07597d119eaa562ccd21c491a095fe0800cf717181115343feb247101007",
          "sha1": "802b385fa0dd9e7ce7f1eff754766c20d6431f5a",
          "md5": "c5071f5f102a7492054f07bb652b6a76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "4a4aaa6b1b775e04b3ae471b31be9a7c7eede7840467dd164fbe4912484f2700858d1e92f98b47ba6df4e754eed0fde96c0874049ed4db6dcef91341c6363a56",
          "sha256": "d14e07597d119eaa562ccd21c491a095fe0800cf717181115343feb247101007",
          "sha1": "802b385fa0dd9e7ce7f1eff754766c20d6431f5a",
          "md5": "c5071f5f102a7492054f07bb652b6a76"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-javadoc.jar",
          "url": "jackson-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "9b16aed593a46923b0ba93184da3d5fa0ab6b0c4111c8de20b6a90f9ac0ce66a6ca3ffce3e0a1cd5d08dd2d4d8328cef5ca53b6f23c474b7deb34e2d45ef2acf",
          "sha256": "0666852d6f24d075ac5003215d515169ff3f5f30a6731be389fdec7b3238407a",
          "sha1": "d252c239a921d422eb9291f767e847bc52985a59",
          "md5": "268844bda930ba92bc3ee63475f04dc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-sources.jar",
          "url": "jackson-1.0.1-beta-sources.jar",
          "size": 9847,
          "sha512": "8802481498d8912b3e7421970458907047ee92e52737a4cdecf6f18789315865b174947c3068000f8fae02b1ee8c1a7fa4009bf4fcd31d5d46be725dbb37fc1e",
          "sha256": "a685e0aa5230ee47c17025f9e3d5c189c19c668be2d4cf5165cb48f816c654a5",
          "sha1": "6b8cdbb5546f882dbed7abf8101505539f29e185",
          "md5": "cd133099e415924ee40157b3eed9bc5d"
        }
      ]
    }
  ]
}
