{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "20c6e2c793040d4c189c6e6acc699c2aef86e035af24cabe700662e246d08b59996380d306358cb133a736e16acb68accfd0d5bf2a672d10173b22800e8e1ee0",
          "sha256": "aca14a8bcf638c86f7eb6b9b2121ff34c9ab6403937713259b81154e9e7e9ac2",
          "sha1": "7145e797f5c3f46ebf0ea914c53092b1139a1e58",
          "md5": "eedd8434256f7aaac85ad0a86819d97c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.1-beta-plain.jar",
          "url": "jackson-1.0.1-beta-plain.jar",
          "size": 16128,
          "sha512": "20c6e2c793040d4c189c6e6acc699c2aef86e035af24cabe700662e246d08b59996380d306358cb133a736e16acb68accfd0d5bf2a672d10173b22800e8e1ee0",
          "sha256": "aca14a8bcf638c86f7eb6b9b2121ff34c9ab6403937713259b81154e9e7e9ac2",
          "sha1": "7145e797f5c3f46ebf0ea914c53092b1139a1e58",
          "md5": "eedd8434256f7aaac85ad0a86819d97c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-javadoc.jar",
          "url": "jackson-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "1f92419ddc1fa2d02d6711ea30b3ad19ab7c3d1a2c0f9534289341b0c9895d6033a462cb8a67ac70370591f4a3c6e453569a4bf9434517f520a1b7d5556b76c8",
          "sha256": "141307b090fe1c7daee3d520d3fc22ec98b90225332fd88d1b4c3d0aa6e3875a",
          "sha1": "66f23c3bdbe52d9e89ed954e7ee9e461ebc411c9",
          "md5": "03abdffa4f785b59ef1100c7976c608a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.1-beta-sources.jar",
          "url": "jackson-1.0.1-beta-sources.jar",
          "size": 9847,
          "sha512": "44b9fc7fb9eff08808d3879eba27d7d013506118bff3146f72e571e5c57de724bc1d219db0d0c1234b968bd5a95c32f8cdddca200f8d8df32818ebcf5a181a14",
          "sha256": "bb4fa82cbcf8f7f05e77a73bd37432289befe37e898a6f6d20bb649826a17a95",
          "sha1": "e1fa499b069959dcfd3f26d00c00ed91bdf81dab",
          "md5": "a710ff9d7222914a98fd8225bf3b2ed6"
        }
      ]
    }
  ]
}
