{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "redis",
    "version": "1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.2-beta-plain.jar",
          "url": "redis-1.0.2-beta-plain.jar",
          "size": 6934,
          "sha512": "5e2e18d326fb441a9d23da053a06b746dde8b797612d8814529d19e8b06f1d610d2b3252e6c80c0c68de1560ca3f106cc8e2b67f5864cbda1afe04c1676e907e",
          "sha256": "416ca6f15e9f34602e7e1ef882c7793725be1c0e33604cad7dfba42bc3767918",
          "sha1": "8442452c5bcf5a8a52f21111e76c753a9ad1cd8e",
          "md5": "4bcab51b860a0ef495ad92f325d423ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.2-beta-plain.jar",
          "url": "redis-1.0.2-beta-plain.jar",
          "size": 6934,
          "sha512": "5e2e18d326fb441a9d23da053a06b746dde8b797612d8814529d19e8b06f1d610d2b3252e6c80c0c68de1560ca3f106cc8e2b67f5864cbda1afe04c1676e907e",
          "sha256": "416ca6f15e9f34602e7e1ef882c7793725be1c0e33604cad7dfba42bc3767918",
          "sha1": "8442452c5bcf5a8a52f21111e76c753a9ad1cd8e",
          "md5": "4bcab51b860a0ef495ad92f325d423ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.2-beta-javadoc.jar",
          "url": "redis-1.0.2-beta-javadoc.jar",
          "size": 261,
          "sha512": "3242975453f89105a99c7608501593db49d62b83b51940272d72eb594c89a4cd373d9068c8d4048a923ff57da58252651fcbc5e483a6b6940081f7883601047e",
          "sha256": "cc7ae9a34775f5faba21e588b5a2b06a535174ae7098cbacdae29a3ae25e404f",
          "sha1": "54ed3b3a8ec60d9865b8d8b249ff37f14aa3b0a4",
          "md5": "9005d5be55721c3f542d918a1f5c42ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.2-beta-sources.jar",
          "url": "redis-1.0.2-beta-sources.jar",
          "size": 3644,
          "sha512": "92bbd816e642394ff343e194c4c02ba01a9f5d18412194d4809e37b820ec080c1695f2fbfb2b8841952ddc9b96b1fce6daad2cd7212959c3da0140adde8ae2a9",
          "sha256": "d8ece397c5f73709755859ddadd33e47b6f510209c09c46e0ce49db01033ba67",
          "sha1": "eda559492db03831f4d5cfba250b61826e0913f6",
          "md5": "e71ad82b7d8fb6be174e00b9e57d5dbf"
        }
      ]
    }
  ]
}
