{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.4-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.4-beta-plain.jar",
          "url": "spring-1.0.4-beta-plain.jar",
          "size": 42458,
          "sha512": "adb5a829d5ac377e06c5a21ec015dba0670ae7b0d298546a095987fa4320623486e517428ef8ab8257fbd866b2f444f35170dcc597ebc075097b3bf8f570f22e",
          "sha256": "d7594b4104e106fefb203c8c850fc0989b2f3b8cad4d3b49f0cd965b8dd6eb3d",
          "sha1": "088cc17bafb6872ed7432279f3c87aea00d26a49",
          "md5": "0260b03be67402f5903c7e20823c44c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.4-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.4-beta-plain.jar",
          "url": "spring-1.0.4-beta-plain.jar",
          "size": 42458,
          "sha512": "adb5a829d5ac377e06c5a21ec015dba0670ae7b0d298546a095987fa4320623486e517428ef8ab8257fbd866b2f444f35170dcc597ebc075097b3bf8f570f22e",
          "sha256": "d7594b4104e106fefb203c8c850fc0989b2f3b8cad4d3b49f0cd965b8dd6eb3d",
          "sha1": "088cc17bafb6872ed7432279f3c87aea00d26a49",
          "md5": "0260b03be67402f5903c7e20823c44c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.4-beta-javadoc.jar",
          "url": "spring-1.0.4-beta-javadoc.jar",
          "size": 261,
          "sha512": "1bd776432ad1ce3e94786ea424cac3319902526d2713adc3801c7efae3c61983b8044cae12107e9dde8f8a21c0c9ff9f91466735cf203c0c93c46df790655474",
          "sha256": "5549ea18c4edf6371887988dbeebbdeb38c967620f0d2d16e55855911bc986c7",
          "sha1": "735bc3607590cd26c6974d5a5f0f461398e8140c",
          "md5": "041b8c13c5e3c25f1e8fddfc81a8b0bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.4-beta-sources.jar",
          "url": "spring-1.0.4-beta-sources.jar",
          "size": 27565,
          "sha512": "4b64bc5658a9bc0ae99640c5c5946f3d3e507153b7d0732b41f5c171431ea7cc509b435b1e1427304042e961f42224924093eda34a6218026e70835b8b653d77",
          "sha256": "5cd4aa07a2e34fb2d2136aafefc5debbf0f62e2497e781850298db540eedeb90",
          "sha1": "1045bbafca6539047fae8985e14527bbebcbd7ea",
          "md5": "8537b3310195d48e507323e135cc9e07"
        }
      ]
    }
  ]
}
