{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.2-beta-plain.jar",
          "url": "database-backup-1.0.2-beta-plain.jar",
          "size": 22740,
          "sha512": "6aae93c9e895a7125557120f4c91fcec1edb9f381fbf76e52e111683c2f27f341252db9442f6743f9df52320971240c5b784d7ed72690af2cf37d959f8e70691",
          "sha256": "da44436e5bb6a9238487853a5f93d894079b6c5f5495422b907a00a230702dd4",
          "sha1": "1782f7437453f50864c608ce3dc6617fc1269f97",
          "md5": "e2500daa9c6d4a2a47c19e39d3b34eac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.2-beta-plain.jar",
          "url": "database-backup-1.0.2-beta-plain.jar",
          "size": 22740,
          "sha512": "6aae93c9e895a7125557120f4c91fcec1edb9f381fbf76e52e111683c2f27f341252db9442f6743f9df52320971240c5b784d7ed72690af2cf37d959f8e70691",
          "sha256": "da44436e5bb6a9238487853a5f93d894079b6c5f5495422b907a00a230702dd4",
          "sha1": "1782f7437453f50864c608ce3dc6617fc1269f97",
          "md5": "e2500daa9c6d4a2a47c19e39d3b34eac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.2-beta-javadoc.jar",
          "url": "database-backup-1.0.2-beta-javadoc.jar",
          "size": 261,
          "sha512": "d4b4bf43919d50712128d4161496977ca7b042b3457edf37195a802bcf0edf25c2e0d1215ac19651a741581afde3462a18fd89bb95cd05a52f9b0aebe2ffe5b4",
          "sha256": "0b31768b115af2794d3b7364ff1b5f9a14474c7d6d1034dc4c9a111360cf1f87",
          "sha1": "016e4eecb5abef108f3afd8b93804c28a2e7a1e7",
          "md5": "43bf3e3f1077fa6233e0a0500e71c196"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.2-beta-sources.jar",
          "url": "database-backup-1.0.2-beta-sources.jar",
          "size": 14674,
          "sha512": "0963a3bb9a6cd41c214adff0b092283aa34b6267f8181bd56329884ef6a83514b1c6d8ce54fc95240290d1eef792f1ca926eca4fc12a71a5e3052d7e37c34a03",
          "sha256": "385bdf74d059aaee9c7b008ef562d12aee3cd64f01145d49e5d25bcea2a2ed0b",
          "sha1": "f3aef644fe711a50110796151baee3c028cc13da",
          "md5": "89fdc8256f0f1d191bfc6da8999ce437"
        }
      ]
    }
  ]
}
