{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "parent",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-plain.jar",
          "url": "parent-1.0.1-beta-plain.jar",
          "size": 261,
          "sha512": "da906fb9f80192713254e2b4d35329378234ab965980253f2a64538bb53cd40019b84bafe7d54d9d8e467822c62dd06d433189659588306546c22c0717c23833",
          "sha256": "7e3ef69e986dd435c0c81aa03b151da74fec93141c2467a38fe2e3e7029d3cbe",
          "sha1": "af7eca00bea77adb4ecb63b105232388da540972",
          "md5": "488938764ae9cca059c138cde4cd6bb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-plain.jar",
          "url": "parent-1.0.1-beta-plain.jar",
          "size": 261,
          "sha512": "da906fb9f80192713254e2b4d35329378234ab965980253f2a64538bb53cd40019b84bafe7d54d9d8e467822c62dd06d433189659588306546c22c0717c23833",
          "sha256": "7e3ef69e986dd435c0c81aa03b151da74fec93141c2467a38fe2e3e7029d3cbe",
          "sha1": "af7eca00bea77adb4ecb63b105232388da540972",
          "md5": "488938764ae9cca059c138cde4cd6bb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-javadoc.jar",
          "url": "parent-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "da906fb9f80192713254e2b4d35329378234ab965980253f2a64538bb53cd40019b84bafe7d54d9d8e467822c62dd06d433189659588306546c22c0717c23833",
          "sha256": "7e3ef69e986dd435c0c81aa03b151da74fec93141c2467a38fe2e3e7029d3cbe",
          "sha1": "af7eca00bea77adb4ecb63b105232388da540972",
          "md5": "488938764ae9cca059c138cde4cd6bb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-sources.jar",
          "url": "parent-1.0.1-beta-sources.jar",
          "size": 261,
          "sha512": "da906fb9f80192713254e2b4d35329378234ab965980253f2a64538bb53cd40019b84bafe7d54d9d8e467822c62dd06d433189659588306546c22c0717c23833",
          "sha256": "7e3ef69e986dd435c0c81aa03b151da74fec93141c2467a38fe2e3e7029d3cbe",
          "sha1": "af7eca00bea77adb4ecb63b105232388da540972",
          "md5": "488938764ae9cca059c138cde4cd6bb6"
        }
      ]
    }
  ]
}
