{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "parent",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-plain.jar",
          "url": "parent-1.0.1-beta-plain.jar",
          "size": 261,
          "sha512": "112ea0b5c017c2698baa60c4511423d4d7cba0f1e7330a775b5bf068f5869d82cc248f291008c2f0603e8de2bbe8c5f021b8ffccc73e50528c287f2d7457d13a",
          "sha256": "7bfc17166bfc1dec07862fb1abe6999b86ffb5798f4347b43b0862017d038710",
          "sha1": "f2ee91d3f7395605874f5aa2ebcfd59bdb8d1496",
          "md5": "118d3c154e713e05f53a08deb65a6506"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-plain.jar",
          "url": "parent-1.0.1-beta-plain.jar",
          "size": 261,
          "sha512": "112ea0b5c017c2698baa60c4511423d4d7cba0f1e7330a775b5bf068f5869d82cc248f291008c2f0603e8de2bbe8c5f021b8ffccc73e50528c287f2d7457d13a",
          "sha256": "7bfc17166bfc1dec07862fb1abe6999b86ffb5798f4347b43b0862017d038710",
          "sha1": "f2ee91d3f7395605874f5aa2ebcfd59bdb8d1496",
          "md5": "118d3c154e713e05f53a08deb65a6506"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-javadoc.jar",
          "url": "parent-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "112ea0b5c017c2698baa60c4511423d4d7cba0f1e7330a775b5bf068f5869d82cc248f291008c2f0603e8de2bbe8c5f021b8ffccc73e50528c287f2d7457d13a",
          "sha256": "7bfc17166bfc1dec07862fb1abe6999b86ffb5798f4347b43b0862017d038710",
          "sha1": "f2ee91d3f7395605874f5aa2ebcfd59bdb8d1496",
          "md5": "118d3c154e713e05f53a08deb65a6506"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.1-beta-sources.jar",
          "url": "parent-1.0.1-beta-sources.jar",
          "size": 261,
          "sha512": "112ea0b5c017c2698baa60c4511423d4d7cba0f1e7330a775b5bf068f5869d82cc248f291008c2f0603e8de2bbe8c5f021b8ffccc73e50528c287f2d7457d13a",
          "sha256": "7bfc17166bfc1dec07862fb1abe6999b86ffb5798f4347b43b0862017d038710",
          "sha1": "f2ee91d3f7395605874f5aa2ebcfd59bdb8d1496",
          "md5": "118d3c154e713e05f53a08deb65a6506"
        }
      ]
    }
  ]
}
