{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 42418,
          "sha512": "ea82b87274847982a09d1650bbe903e40ef8172438df5449fef38f7e07a163835836a82b692934086ce02455bc30bb9c76dd83a1eebf6ad1e4d586f9b8a816d8",
          "sha256": "bfa16259fc05fc0432e796da90cbf9eab0721b0143132bfb800f85fa84bf15ab",
          "sha1": "700329ccc8568a0cb95ee52f4835e67ffcb75f68",
          "md5": "406a9b1bf660248d7713970594fb3f1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 42418,
          "sha512": "ea82b87274847982a09d1650bbe903e40ef8172438df5449fef38f7e07a163835836a82b692934086ce02455bc30bb9c76dd83a1eebf6ad1e4d586f9b8a816d8",
          "sha256": "bfa16259fc05fc0432e796da90cbf9eab0721b0143132bfb800f85fa84bf15ab",
          "sha1": "700329ccc8568a0cb95ee52f4835e67ffcb75f68",
          "md5": "406a9b1bf660248d7713970594fb3f1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-javadoc.jar",
          "url": "spring-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "4abf51106c4777f16de1e6673ecd4a09a2f018543eaf1035ec677732e6159316c947849fa7fe8ed72e831e8f12f1c4c19327851241586ab1134d3ca4e1b93547",
          "sha256": "49352d480582141e980212f9f088163b1a824a1e7936c5bef8172534e61465f2",
          "sha1": "686da51826e35c31457e0869961d52cb17300471",
          "md5": "27faab1bc02038748d6fa75b471d478b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-sources.jar",
          "url": "spring-1.0.1-beta-sources.jar",
          "size": 27504,
          "sha512": "45ff5a7e38fde9543c39b9f7cf3b913c898cdbcb575df1a671ce3486a4d0d63804e8e646711adc769f0462ff0c8199c8cc607c84fbaba384e3ad6d3a976f9f5e",
          "sha256": "7d4cc1666527e28c5c78a133e5b9e65be7fabf94b60be7cdf27d8fd27476a0b7",
          "sha1": "46f993349add38e323e17d968c1ac005554b2c8d",
          "md5": "0c876d78acb60a16a3d627b9baf1b67d"
        }
      ]
    }
  ]
}
