{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 39293,
          "sha512": "3c08e43dfdfffa32919646db9af1d4308abdd9b9e944a489b72d113f8248ae55761a59a80ee4f93632a03afff57a406628b9c4aa1ff207f76eba8f5d4d026bd5",
          "sha256": "f94230b85aac89de519fdfc4e7d0d967495044823c957c4e365d363d2f7ea0aa",
          "sha1": "8d149d092ba55bf6ec2455fc24de9c0096fdede7",
          "md5": "d7220e9b17e7bda0f90e9806b2678c20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 39293,
          "sha512": "3c08e43dfdfffa32919646db9af1d4308abdd9b9e944a489b72d113f8248ae55761a59a80ee4f93632a03afff57a406628b9c4aa1ff207f76eba8f5d4d026bd5",
          "sha256": "f94230b85aac89de519fdfc4e7d0d967495044823c957c4e365d363d2f7ea0aa",
          "sha1": "8d149d092ba55bf6ec2455fc24de9c0096fdede7",
          "md5": "d7220e9b17e7bda0f90e9806b2678c20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-javadoc.jar",
          "url": "spring-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "4abf51106c4777f16de1e6673ecd4a09a2f018543eaf1035ec677732e6159316c947849fa7fe8ed72e831e8f12f1c4c19327851241586ab1134d3ca4e1b93547",
          "sha256": "49352d480582141e980212f9f088163b1a824a1e7936c5bef8172534e61465f2",
          "sha1": "686da51826e35c31457e0869961d52cb17300471",
          "md5": "27faab1bc02038748d6fa75b471d478b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-sources.jar",
          "url": "spring-1.0.1-beta-sources.jar",
          "size": 25548,
          "sha512": "8131832d6053783e9ba5f46d074df89c4fdc2d7454581d358b42b0eee97cfc34b9914c38605b66a08f56c5b0cfb181c7f9b11063623e54434adba53b1bfbc868",
          "sha256": "746fa9d85470139ba5a181c675581f1dc34bd9fe10b5070ea1d6469451c89584",
          "sha1": "c1d236b2ed94fe13b0464ae4eeb0fef7996479d0",
          "md5": "bc54e5aff695e6cc9c7c1fb1d9a0f4ff"
        }
      ]
    }
  ]
}
