{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 37806,
          "sha512": "98e9c57357dee24e03bc8ce9039c2ce375125d0eb9e522402ccb1f5b69eed9eb803f35ffd0c6caea6a35f2b1abc490521598ed6b9575535e97121b2f6cd75543",
          "sha256": "a96268e22299c205496ae673372bfb3ee6944653c94b204f7f5bedfba87b6f25",
          "sha1": "5c45e75aed20e2913a6e0b812c79fc38bb167675",
          "md5": "836f70ebea1ff9b287826831d32b71f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.1-beta-plain.jar",
          "url": "spring-1.0.1-beta-plain.jar",
          "size": 37806,
          "sha512": "98e9c57357dee24e03bc8ce9039c2ce375125d0eb9e522402ccb1f5b69eed9eb803f35ffd0c6caea6a35f2b1abc490521598ed6b9575535e97121b2f6cd75543",
          "sha256": "a96268e22299c205496ae673372bfb3ee6944653c94b204f7f5bedfba87b6f25",
          "sha1": "5c45e75aed20e2913a6e0b812c79fc38bb167675",
          "md5": "836f70ebea1ff9b287826831d32b71f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-javadoc.jar",
          "url": "spring-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "4abf51106c4777f16de1e6673ecd4a09a2f018543eaf1035ec677732e6159316c947849fa7fe8ed72e831e8f12f1c4c19327851241586ab1134d3ca4e1b93547",
          "sha256": "49352d480582141e980212f9f088163b1a824a1e7936c5bef8172534e61465f2",
          "sha1": "686da51826e35c31457e0869961d52cb17300471",
          "md5": "27faab1bc02038748d6fa75b471d478b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.1-beta-sources.jar",
          "url": "spring-1.0.1-beta-sources.jar",
          "size": 24776,
          "sha512": "9c982c5f1b84c1f876c87d73422d186eab82d29f7e59eebc758532d050e5cfc022578419aa11741eb092b71a8372504649a5717cf27aaafdbb19ad3c25687215",
          "sha256": "acb62d47719abd261d687be21d562e7ac4902224be3f9e7b6ef084ab332159e2",
          "sha1": "7730c17a4c7acd70e532a5cd7982b1f84f23491d",
          "md5": "836f0ab8b2e415e4d37d93ff6d7bd913"
        }
      ]
    }
  ]
}
