{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "aliyun",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 152948,
          "sha512": "6961c9be216abaff99960a151b27f31658a5139a0854505fb6444a1907d197c20cd5cebb6b9ef0dccbba880b9abe32ee114f101b008787979987027b75231800",
          "sha256": "a3cd281bb14e17754b18eea1fb64fe1b8831fa313d4eafc4fad07f9ca79a7a54",
          "sha1": "82ea231b3334177f1820d713d6654858cfa58667",
          "md5": "39398c04e65d50d17dbc5457b35c6cb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "aliyun",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 152948,
          "sha512": "6961c9be216abaff99960a151b27f31658a5139a0854505fb6444a1907d197c20cd5cebb6b9ef0dccbba880b9abe32ee114f101b008787979987027b75231800",
          "sha256": "a3cd281bb14e17754b18eea1fb64fe1b8831fa313d4eafc4fad07f9ca79a7a54",
          "sha1": "82ea231b3334177f1820d713d6654858cfa58667",
          "md5": "39398c04e65d50d17dbc5457b35c6cb8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-javadoc.jar",
          "url": "security-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "de429c47811efa6da166a0689ea9f390751885db17b02f4de4fb4049f32b5f6bea1ff30f1477260c299bb49ff45d8385148413d4ee8614c426c9e40893b77c7c",
          "sha256": "086a0eda962f5b87b5cd81816f7294e9b6b261633b246f069f67975001202d1b",
          "sha1": "bcd36d07a60c398a07d682e7f1b4f0d7f194a5e8",
          "md5": "50c5e45d5487406596bf178c3dbb43d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-sources.jar",
          "url": "security-1.0.1-beta-sources.jar",
          "size": 98111,
          "sha512": "45e5f2326b4c3d9eaf916dc7fb02ca21e4a8f362f04ede066e81a17692c0032e95f9ef8694d07ff9601f307a0f4dbc657b999270535f83fb0536dc9ce4b97e16",
          "sha256": "1bbd342b9754e1911c951350345b6f628c7dc1a007c2af73afd39118d328e454",
          "sha1": "90592823be33ef478144c2cede98a412bf258190",
          "md5": "ea3292ccb3be32246c08a2441b1fd45a"
        }
      ]
    }
  ]
}
