{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 135504,
          "sha512": "77c63ed012d3f2c6107d54215eba386e0f7425b427f83a3b902c72f1aeb8dcf9b3a1bf5abf942f466c72727486fcf18619ee9926c948698ab79382ba1f0b218b",
          "sha256": "248fbd0a4d0192de9ed46223dea11951bc6236786b2d565cb3c948c89febb861",
          "sha1": "df428b783cb57f1f8ea55de3805807dfddfd923e",
          "md5": "ede4b451be5604e049fe1452d8364305"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 135504,
          "sha512": "77c63ed012d3f2c6107d54215eba386e0f7425b427f83a3b902c72f1aeb8dcf9b3a1bf5abf942f466c72727486fcf18619ee9926c948698ab79382ba1f0b218b",
          "sha256": "248fbd0a4d0192de9ed46223dea11951bc6236786b2d565cb3c948c89febb861",
          "sha1": "df428b783cb57f1f8ea55de3805807dfddfd923e",
          "md5": "ede4b451be5604e049fe1452d8364305"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-javadoc.jar",
          "url": "security-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "4abf51106c4777f16de1e6673ecd4a09a2f018543eaf1035ec677732e6159316c947849fa7fe8ed72e831e8f12f1c4c19327851241586ab1134d3ca4e1b93547",
          "sha256": "49352d480582141e980212f9f088163b1a824a1e7936c5bef8172534e61465f2",
          "sha1": "686da51826e35c31457e0869961d52cb17300471",
          "md5": "27faab1bc02038748d6fa75b471d478b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-sources.jar",
          "url": "security-1.0.1-beta-sources.jar",
          "size": 85870,
          "sha512": "86243c737702ad283e6eb0f8091a3d6fabadd0425683773c2092ba97b5e994b06309916e90e7c8570b1e3c32947a6f70464cfe01af409f6fe73193ca2b73a2ca",
          "sha256": "8a4dce4daad30cea58c7e8361baa36852480db35977d7df96681faf7302fe458",
          "sha1": "ddc53894b22f27b36ed988b50cef8aeb6c53ca59",
          "md5": "7a9e08000c7ed796bda98f726333a28f"
        }
      ]
    }
  ]
}
