{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 136112,
          "sha512": "4f87c7c492fc40f6c5354ffc65710e8e76da3552bfc8bf928ada39d4e0b6dc049041fdf938daa7017d03289ba12178fbc7b214a468ae501fd14fe4cf9602d4fe",
          "sha256": "45317c2d34d21ac225fd35355eeb0be91f366b884f8bb5a8ef9e63d6688fea2a",
          "sha1": "04b46fd0ec6007c3e8e4a765e9048c81112031c2",
          "md5": "ecd78a50824c1b093ef9af3439eae270"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.1-beta-plain.jar",
          "url": "security-1.0.1-beta-plain.jar",
          "size": 136112,
          "sha512": "4f87c7c492fc40f6c5354ffc65710e8e76da3552bfc8bf928ada39d4e0b6dc049041fdf938daa7017d03289ba12178fbc7b214a468ae501fd14fe4cf9602d4fe",
          "sha256": "45317c2d34d21ac225fd35355eeb0be91f366b884f8bb5a8ef9e63d6688fea2a",
          "sha1": "04b46fd0ec6007c3e8e4a765e9048c81112031c2",
          "md5": "ecd78a50824c1b093ef9af3439eae270"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-javadoc.jar",
          "url": "security-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "4abf51106c4777f16de1e6673ecd4a09a2f018543eaf1035ec677732e6159316c947849fa7fe8ed72e831e8f12f1c4c19327851241586ab1134d3ca4e1b93547",
          "sha256": "49352d480582141e980212f9f088163b1a824a1e7936c5bef8172534e61465f2",
          "sha1": "686da51826e35c31457e0869961d52cb17300471",
          "md5": "27faab1bc02038748d6fa75b471d478b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.1-beta-sources.jar",
          "url": "security-1.0.1-beta-sources.jar",
          "size": 86351,
          "sha512": "76374e55cd5434870030043e2d7f79cf6aab78dd101db82e846bf0a92939842c593685446a107b939c4003565ff6572ae6d505a63f462e9b62b534f75699b48f",
          "sha256": "c3599d4f2b5fd5cced4107845374d64bbac061275285fbc74ac21a16c7a110cb",
          "sha1": "46f4a671661412ccc444c7913373579dd6ee24ea",
          "md5": "36f3a65af2cbe813171405564cc45a5a"
        }
      ]
    }
  ]
}
