spring:
  profiles:
    active: template-dev
  config:
    import:
      - application-common.yml
      - application-database.yml
      - application-system.yml
      - application-wechat.yml
      - application-aliyun.yml