logging:
  level:
    com.gin: debug

spring:
  datasource:

    #    url: jdbc:mysql://192.168.0.10:3306/cams?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    #    url: jdbc:mysql://localhost:3306/spring-boot-3-template?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: lzbx2837200
  data:
    redis:
      host: 192.168.0.10
      password: lzbx2837200
      database: 2
#      database: 15
