{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "redis",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.1-beta-plain.jar",
          "url": "redis-1.0.1-beta-plain.jar",
          "size": 6934,
          "sha512": "b8b656abac65701d3aef0bfccd364a7dbb48b01383f24d32dcbe878f2dfa6b6492a81a1a1026f0607b66970b1a78ce030a16438bfce557da02b41c7713ad0097",
          "sha256": "1faf1dc3ff387202b5a2b37bd8991db9cfca3e065449bd0a5041ec34b56a634d",
          "sha1": "846e5680916cc3d99902430ca1e10aed150c8db7",
          "md5": "0ee06f29aa34ddc6fdcac606c7b90159"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.1-beta-plain.jar",
          "url": "redis-1.0.1-beta-plain.jar",
          "size": 6934,
          "sha512": "b8b656abac65701d3aef0bfccd364a7dbb48b01383f24d32dcbe878f2dfa6b6492a81a1a1026f0607b66970b1a78ce030a16438bfce557da02b41c7713ad0097",
          "sha256": "1faf1dc3ff387202b5a2b37bd8991db9cfca3e065449bd0a5041ec34b56a634d",
          "sha1": "846e5680916cc3d99902430ca1e10aed150c8db7",
          "md5": "0ee06f29aa34ddc6fdcac606c7b90159"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.1-beta-javadoc.jar",
          "url": "redis-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "9cfb295bba4a92616bcba13472bbc9e69055b614319f426d187f42efc6648764701102120491d81eaca2fd13587dc8ea7e1f567b8685b30275259cb398448eee",
          "sha256": "11fee9445b031c48177cf0ccf7320e33433a83647d9e76aa551c2d82ac54763b",
          "sha1": "220cfbb5ef6a05159e1219f34b7e75d0550febb7",
          "md5": "d81740e0badfb5dde1377ecd2a93f815"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.1-beta-sources.jar",
          "url": "redis-1.0.1-beta-sources.jar",
          "size": 3644,
          "sha512": "1a3ea0106d99d7762ef93c62fc2adc79564aa44fa871ecb8e71b0f03a5e0dcf951054577bc1fdcb00a57367fd0860344a7a1870f7f7bbd85ae43e1b7d30545a9",
          "sha256": "6d7d0761579beb774ddcb0541a4ab800f9f6af025a432946fef2b435609a31a3",
          "sha1": "a2dea601159bbe48de9d0728b658c4b0d5534bd7",
          "md5": "f30e34819b15335eea780932d982e4fa"
        }
      ]
    }
  ]
}
