{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "redis",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.1-beta-plain.jar",
          "url": "redis-1.0.1-beta-plain.jar",
          "size": 6934,
          "sha512": "37e7bb3d03d174cff3aa3e5a11817b444313a2e3ccc7455023eb428036324e358c386434218d57b04653aaeebd8e2b259b4cdc4dbae7dc764994e8df905fd077",
          "sha256": "4a960b67aede08e6124d596d83be64e54db64ad6ab3d50efe379a3437954961c",
          "sha1": "ab8b7719ba0f698b5d65b3bed850eee07709663a",
          "md5": "9e8a1314ebb5d9055ccdc75bc237b642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.1-beta-plain.jar",
          "url": "redis-1.0.1-beta-plain.jar",
          "size": 6934,
          "sha512": "37e7bb3d03d174cff3aa3e5a11817b444313a2e3ccc7455023eb428036324e358c386434218d57b04653aaeebd8e2b259b4cdc4dbae7dc764994e8df905fd077",
          "sha256": "4a960b67aede08e6124d596d83be64e54db64ad6ab3d50efe379a3437954961c",
          "sha1": "ab8b7719ba0f698b5d65b3bed850eee07709663a",
          "md5": "9e8a1314ebb5d9055ccdc75bc237b642"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.1-beta-javadoc.jar",
          "url": "redis-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "ccfb49025278a6524085f590498f5d7426bde7c820d264c220a7b529f906d2cc36dea86d887da52d39f3e767a5efe81acb710241f39d4320dd0ea15867c51346",
          "sha256": "d81530a1de64e7c4d501db5300f4d42b45f692b55116156af66e6659b3ee8076",
          "sha1": "b86447b040b06cd17890f0e37f387d0932b847d6",
          "md5": "9c8d05d3e51c536809a40492ccd03e64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.1-beta-sources.jar",
          "url": "redis-1.0.1-beta-sources.jar",
          "size": 3644,
          "sha512": "bb019184849f0e8162093a170f8e452446d011fad3249880b33a20938cc8b014f1fcf60a307b0a1a4932ace389b450db7c83fd5d987dd3c25fc0532402644496",
          "sha256": "751916d444c72a59c18482197c8fa2cc34b68d34ee97fbc829d65e70df8ec47d",
          "sha1": "8a839f44e41a56c9ae6b1bc564e74b1fb97c249e",
          "md5": "c6ad81a220329bf5932ea38ee542bbe3"
        }
      ]
    }
  ]
}
