{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "parent",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-1.0.0-plain.jar",
          "url": "parent-1.0.0-plain.jar",
          "size": 261,
          "sha512": "a0de32128706b271480f4b92622dbbd581581e8d3b8c58298d4fde08c29d31513cd161aa427709e61f6c29521b2169e47e84d1e5fe7c75e037be5dc03b689712",
          "sha256": "ddfd05663a7e6d04de3e58ff56be9123ffb97af0f32fff10749ba902142d062e",
          "sha1": "8e52c2eef53101e05665f85aa95003ffeab88075",
          "md5": "a702bb225fc0200916fd7eeeb907e7c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-plain.jar",
          "url": "parent-1.0.0-plain.jar",
          "size": 261,
          "sha512": "a0de32128706b271480f4b92622dbbd581581e8d3b8c58298d4fde08c29d31513cd161aa427709e61f6c29521b2169e47e84d1e5fe7c75e037be5dc03b689712",
          "sha256": "ddfd05663a7e6d04de3e58ff56be9123ffb97af0f32fff10749ba902142d062e",
          "sha1": "8e52c2eef53101e05665f85aa95003ffeab88075",
          "md5": "a702bb225fc0200916fd7eeeb907e7c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-javadoc.jar",
          "url": "parent-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "a0de32128706b271480f4b92622dbbd581581e8d3b8c58298d4fde08c29d31513cd161aa427709e61f6c29521b2169e47e84d1e5fe7c75e037be5dc03b689712",
          "sha256": "ddfd05663a7e6d04de3e58ff56be9123ffb97af0f32fff10749ba902142d062e",
          "sha1": "8e52c2eef53101e05665f85aa95003ffeab88075",
          "md5": "a702bb225fc0200916fd7eeeb907e7c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-sources.jar",
          "url": "parent-1.0.0-sources.jar",
          "size": 261,
          "sha512": "a0de32128706b271480f4b92622dbbd581581e8d3b8c58298d4fde08c29d31513cd161aa427709e61f6c29521b2169e47e84d1e5fe7c75e037be5dc03b689712",
          "sha256": "ddfd05663a7e6d04de3e58ff56be9123ffb97af0f32fff10749ba902142d062e",
          "sha1": "8e52c2eef53101e05665f85aa95003ffeab88075",
          "md5": "a702bb225fc0200916fd7eeeb907e7c1"
        }
      ]
    }
  ]
}
