{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "parent",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "parent-1.0.0-plain.jar",
          "url": "parent-1.0.0-plain.jar",
          "size": 261,
          "sha512": "79fe092927ef0cd2642f9a556f1f704f970fcc6c9fb0ed83e4616060964a171f6fbeba8937c583476215965ddbbae4422e9cf8e6efb51b788cfec55a39b205f8",
          "sha256": "4f0b59648d1272f7bed9b7a6557e6e3e13b95cc11b5a4f5d51eacc7bff0807fb",
          "sha1": "0ad520987bbe3b9e2f22e3b42d477853573e64b0",
          "md5": "80e1ff665f8818b2415c807fc0f06607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-plain.jar",
          "url": "parent-1.0.0-plain.jar",
          "size": 261,
          "sha512": "79fe092927ef0cd2642f9a556f1f704f970fcc6c9fb0ed83e4616060964a171f6fbeba8937c583476215965ddbbae4422e9cf8e6efb51b788cfec55a39b205f8",
          "sha256": "4f0b59648d1272f7bed9b7a6557e6e3e13b95cc11b5a4f5d51eacc7bff0807fb",
          "sha1": "0ad520987bbe3b9e2f22e3b42d477853573e64b0",
          "md5": "80e1ff665f8818b2415c807fc0f06607"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-javadoc.jar",
          "url": "parent-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "d9bdbe66f461ff74c5920e8eb76ef677096a302f91e051c52781c8240705d247a7f391068577c12c1b40bd07069c50cc945bddce07715344a21f24f16e916659",
          "sha256": "66e43ff0b91640c4bce14e3afe313a9f7926e7ebc3add45dd0f376e41c6267da",
          "sha1": "5b581f58dcf7425af3eb235e6ce59bbc38e1a1af",
          "md5": "36d91aa9419e6461e53962377867bfbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "parent-1.0.0-sources.jar",
          "url": "parent-1.0.0-sources.jar",
          "size": 261,
          "sha512": "d9bdbe66f461ff74c5920e8eb76ef677096a302f91e051c52781c8240705d247a7f391068577c12c1b40bd07069c50cc945bddce07715344a21f24f16e916659",
          "sha256": "66e43ff0b91640c4bce14e3afe313a9f7926e7ebc3add45dd0f376e41c6267da",
          "sha1": "5b581f58dcf7425af3eb235e6ce59bbc38e1a1af",
          "md5": "36d91aa9419e6461e53962377867bfbc"
        }
      ]
    }
  ]
}
