{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 28049,
          "sha512": "8d01082f615b55c1f0f18c44082ef88ba843ce01b4db71be2d8b3a36aef124b20d7e9c955778af885fcdfd8bf64c5d86b52f7e8184e9f8558549e2d479128dd0",
          "sha256": "612c2d1ae71be83a6ae96528e190805c028eeaed8f7f7127b37ca78e1b616a5a",
          "sha1": "17122f2dd03113a1adbc44440b13dd519cf4aebd",
          "md5": "1524d9e4005f98bffef9250735c94e23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 28049,
          "sha512": "8d01082f615b55c1f0f18c44082ef88ba843ce01b4db71be2d8b3a36aef124b20d7e9c955778af885fcdfd8bf64c5d86b52f7e8184e9f8558549e2d479128dd0",
          "sha256": "612c2d1ae71be83a6ae96528e190805c028eeaed8f7f7127b37ca78e1b616a5a",
          "sha1": "17122f2dd03113a1adbc44440b13dd519cf4aebd",
          "md5": "1524d9e4005f98bffef9250735c94e23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-javadoc.jar",
          "url": "spring-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7b7a3be588d898d29f4135ed7b5981279a0b518b17d92f313a5369367561c70f95e666c2e91b9aa361a4cc625a928fb8c6ae5d3e45383db794aa2e092532b69e",
          "sha256": "ad56729b478af841239e575baade443b9ba419320284afe291ab521a279646db",
          "sha1": "851cdeea6617510a3445358fb3f187b11cab83c6",
          "md5": "542397d5212f45a776bc298ee54e7f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-sources.jar",
          "url": "spring-1.0.0-sources.jar",
          "size": 18766,
          "sha512": "37c8f095a38e362dcbe54741e93b93d768a0d49a83a91002e5e2807878b365685e88b515ec0495e94c67db044e1bc504c472582b73a75d9575a84a6d42c08b85",
          "sha256": "3570fb79f3f5310100b7b25d9688d49b04a86c9076c829310e64d1b068ce50cf",
          "sha1": "5f76d5c079de86d33781d38de7e36088540d5e60",
          "md5": "89ff1c1c4edf12fe19185c20b8680409"
        }
      ]
    }
  ]
}
