{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 37093,
          "sha512": "cf4a5202654340af07d21c68837596ceed6e7519a252b3db40cded89597f02e2459a9519ffd14e808dc10d1eff509b4f525bfde52e8f4dc8ff0a192e54e03b53",
          "sha256": "4cbfd70e7c5d93f5bab21aa4b1de732e2b59ff6964722764b9dab52e759f06b5",
          "sha1": "121de64b5f10cfffc81c74986408c2b651db66a9",
          "md5": "0a08b1232908fd347a0df65966eec7b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 37093,
          "sha512": "cf4a5202654340af07d21c68837596ceed6e7519a252b3db40cded89597f02e2459a9519ffd14e808dc10d1eff509b4f525bfde52e8f4dc8ff0a192e54e03b53",
          "sha256": "4cbfd70e7c5d93f5bab21aa4b1de732e2b59ff6964722764b9dab52e759f06b5",
          "sha1": "121de64b5f10cfffc81c74986408c2b651db66a9",
          "md5": "0a08b1232908fd347a0df65966eec7b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-javadoc.jar",
          "url": "spring-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7b7a3be588d898d29f4135ed7b5981279a0b518b17d92f313a5369367561c70f95e666c2e91b9aa361a4cc625a928fb8c6ae5d3e45383db794aa2e092532b69e",
          "sha256": "ad56729b478af841239e575baade443b9ba419320284afe291ab521a279646db",
          "sha1": "851cdeea6617510a3445358fb3f187b11cab83c6",
          "md5": "542397d5212f45a776bc298ee54e7f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-sources.jar",
          "url": "spring-1.0.0-sources.jar",
          "size": 24369,
          "sha512": "9d7eb36f9ffc3d6547436e854ce53c5b5fa495632af4fc71b8936847387164ce2a4d141cc612b2044be7551a8d1ad6d5b938863c2d3126db6b5ad3246f4c20dc",
          "sha256": "c3095c3e3ae7c1d23de56792a45d82b50dcc11276dbd5229101d56d5445f9ea2",
          "sha1": "0d7a4d5b2fc034484ff8fbde8af66464263b5edf",
          "md5": "2d78a01b883da32fc7782dc50a4ad505"
        }
      ]
    }
  ]
}
