{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 37093,
          "sha512": "548523558ecff3846cb0bb1cbdce7b09818af672b357e2974b5442ff5d7491341acaca45b3a6fbf396ae1dd9c5fb44da743b02d6e7efe051cc8d63dd8f85ea0a",
          "sha256": "8f50859fa768466435ec187fac99e30dc22e75a5a2aa4469939cb898fef2b8a6",
          "sha1": "128bbbcdc3f443550a7fabb8d751d87919698a08",
          "md5": "283f06b571f953e34a07419a705ba9c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.0-plain.jar",
          "url": "spring-1.0.0-plain.jar",
          "size": 37093,
          "sha512": "548523558ecff3846cb0bb1cbdce7b09818af672b357e2974b5442ff5d7491341acaca45b3a6fbf396ae1dd9c5fb44da743b02d6e7efe051cc8d63dd8f85ea0a",
          "sha256": "8f50859fa768466435ec187fac99e30dc22e75a5a2aa4469939cb898fef2b8a6",
          "sha1": "128bbbcdc3f443550a7fabb8d751d87919698a08",
          "md5": "283f06b571f953e34a07419a705ba9c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-javadoc.jar",
          "url": "spring-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "37edece4f4b0b3b3b0d79cc054450132edd2745d3a7f3040c3ed3f0ab6c62f1e7553ea553e6e5b0e5b4c3ab55f350592d00dd9a84989bf2d8abe97d7511f1094",
          "sha256": "f13f7bd62d86a1e561da83f664c10610164a4c412ed9d23f6aecbdf1e49c94a5",
          "sha1": "7f6aab7fffa8037745640788f66c7bdeda417f14",
          "md5": "74e2c6663e9ffadd028c7b83b604562b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.0-sources.jar",
          "url": "spring-1.0.0-sources.jar",
          "size": 24369,
          "sha512": "b4a4396be72926b299452c1aee94c24b8cbf7eab6c576dc515b4eb842a4aa74ad25cdf3556a95ad96a6d04f587af9bdf2fe17f206ca578986a7251d203cd6bf8",
          "sha256": "3f69e349c3c03ff01a378943d7ead141c6e4b9497378be13ec9c4c15a52b0c3f",
          "sha1": "d827a1b81da1a18067889f42cc76bf85457c31dc",
          "md5": "a8ece27a84e057e2751d0f7da4ad29e6"
        }
      ]
    }
  ]
}
