{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.2-beta-plain.jar",
          "url": "app-1.0.2-beta-plain.jar",
          "size": 6350,
          "sha512": "85699bfb56948cea403e07e0746edb1f06ce377259b3ef51c7d6a86ba41bc2b5eaba32cd744508a1edae4d3867f6893a1a3193ff68cfec6c029bbcfdf4a1e3c3",
          "sha256": "bee0574a061382066f04f3810a7ab19fb56d1003322de56ac37203ce71db7458",
          "sha1": "3cf3dd13c919bac12f2edcb98298057fcd7b2e44",
          "md5": "93b6f7d3ea2ee02320e4b7b8bb58d378"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.2-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.2-beta-plain.jar",
          "url": "app-1.0.2-beta-plain.jar",
          "size": 6350,
          "sha512": "85699bfb56948cea403e07e0746edb1f06ce377259b3ef51c7d6a86ba41bc2b5eaba32cd744508a1edae4d3867f6893a1a3193ff68cfec6c029bbcfdf4a1e3c3",
          "sha256": "bee0574a061382066f04f3810a7ab19fb56d1003322de56ac37203ce71db7458",
          "sha1": "3cf3dd13c919bac12f2edcb98298057fcd7b2e44",
          "md5": "93b6f7d3ea2ee02320e4b7b8bb58d378"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.2-beta-javadoc.jar",
          "url": "app-1.0.2-beta-javadoc.jar",
          "size": 261,
          "sha512": "d4b4bf43919d50712128d4161496977ca7b042b3457edf37195a802bcf0edf25c2e0d1215ac19651a741581afde3462a18fd89bb95cd05a52f9b0aebe2ffe5b4",
          "sha256": "0b31768b115af2794d3b7364ff1b5f9a14474c7d6d1034dc4c9a111360cf1f87",
          "sha1": "016e4eecb5abef108f3afd8b93804c28a2e7a1e7",
          "md5": "43bf3e3f1077fa6233e0a0500e71c196"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.2-beta-sources.jar",
          "url": "app-1.0.2-beta-sources.jar",
          "size": 5018,
          "sha512": "270aee58d3d2271f7a7c4c0541c821077494bb78e0f3c7930265855ed1c7e7c62d4e538c60dad39ee2fadb8478801a619723f9ec81420d77d3fddfe43d9a061b",
          "sha256": "055ca9b27a9a131f7e706829c3688a935f129d6770422ed2edd832f225f172c2",
          "sha1": "5a3664dea61d49df3ece0235256046d8ab2c935c",
          "md5": "6ce5e6ec9553fe32dc6647c49141ca97"
        }
      ]
    }
  ]
}
