{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "0ee105c22ada8ef1f89284eef8d028a9711ba1bc56c0a4427c6acc70e1dc207f92dda89ee74bd870893daf88b018efeaa568811a8c0cf168a65358c46243f88b",
          "sha256": "6c850c36b790e32f20ddfa031c1e4125c2271052ac4d9ccb68513765daf9eb3c",
          "sha1": "be58a69d71896c8a6bd84d82d4389dc3298959e7",
          "md5": "9a9b067b529a0242c4b42d981ccdc636"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.0-plain.jar",
          "url": "app-1.0.0-plain.jar",
          "size": 3743,
          "sha512": "0ee105c22ada8ef1f89284eef8d028a9711ba1bc56c0a4427c6acc70e1dc207f92dda89ee74bd870893daf88b018efeaa568811a8c0cf168a65358c46243f88b",
          "sha256": "6c850c36b790e32f20ddfa031c1e4125c2271052ac4d9ccb68513765daf9eb3c",
          "sha1": "be58a69d71896c8a6bd84d82d4389dc3298959e7",
          "md5": "9a9b067b529a0242c4b42d981ccdc636"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-javadoc.jar",
          "url": "app-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "5126c4ff2f50a3a8f9195cdce8c386cb904362197c688f358a3e3b26389ce1c4407bd554dedc6f79f5faedbe338097c0bb7fb0172cf63794684af06a2b2f0aab",
          "sha256": "59b1af4423b0a75563106bb68c7c34e022b4d704ffc9298cd2b824c5fbe3bb93",
          "sha1": "f2746e2963c32f500ae58cd96bca15e5c63fb73b",
          "md5": "c0f18df61d0ed6c28a092726bfcbf46c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.0-sources.jar",
          "url": "app-1.0.0-sources.jar",
          "size": 3538,
          "sha512": "e22fb87f9961d41d4df144a718f9ac6b48f3d724c683675c9cc1fc337a97367b20ea6083d92e322031076a86049808ccb44c16a05a636db97d252d4524146454",
          "sha256": "0ce90d31cb0d3a68a870d44c6ef258e894f716a256d8db2b499af2dd377cd2af",
          "sha1": "66b294b71cf933d37e4faba374a3e91c5a6f950f",
          "md5": "8499d4b968ccb4e4ae48dfe2a5f1bbf9"
        }
      ]
    }
  ]
}
