{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "route",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.1-beta-plain.jar",
          "url": "route-1.0.1-beta-plain.jar",
          "size": 19313,
          "sha512": "04334c078c6b2b9d9921eeae65f6f12d4bf5e4ca146848206b00d30b94285fc080d6d96ca712cc1ea69529d64d077b88ebcee21b6f2ffd035ef3b3d3caa8f581",
          "sha256": "aac782ae223ad6966af6d4f7dc6f4a4e7b915d72f413474b651c9b4d63e08a7c",
          "sha1": "5a5ba746d2eadf370e7673a0d4fdd0f31d673e40",
          "md5": "6bc9a84e76258e0970586a2356f0e720"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.1-beta-plain.jar",
          "url": "route-1.0.1-beta-plain.jar",
          "size": 19313,
          "sha512": "04334c078c6b2b9d9921eeae65f6f12d4bf5e4ca146848206b00d30b94285fc080d6d96ca712cc1ea69529d64d077b88ebcee21b6f2ffd035ef3b3d3caa8f581",
          "sha256": "aac782ae223ad6966af6d4f7dc6f4a4e7b915d72f413474b651c9b4d63e08a7c",
          "sha1": "5a5ba746d2eadf370e7673a0d4fdd0f31d673e40",
          "md5": "6bc9a84e76258e0970586a2356f0e720"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.1-beta-javadoc.jar",
          "url": "route-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "de8855ba0efc3c297b881bd4ce028a8ba7b7188bfb148736910be453892e2ee878662a96319d43a94caeb67273058210db6c09079ff45da781918a0c347985bb",
          "sha256": "3d8bfdef1f136569f70e14a8b52760151d63cc1e763f7dd5abee6244546f9ca0",
          "sha1": "f9606eb4090119874b4f479d828a11486577187c",
          "md5": "1beb9734685dcbc065e7acc48945d366"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.1-beta-sources.jar",
          "url": "route-1.0.1-beta-sources.jar",
          "size": 13582,
          "sha512": "47f32afb6d883201b179494a19d6066e855994c93a1fa99c23905e81c48326fd4b5d4bca59428bb388a79a83adde0a98255cbda45809a32a0f5adda21b8bd623",
          "sha256": "90591715313e1c384a663bbfbcedb3e895bdbbccbab2583797409d39fe9a65bf",
          "sha1": "c9ce733e80abe9b4480cd66ec04404bbce430054",
          "md5": "6490a76030bd3929e383bd8dfb28b39a"
        }
      ]
    }
  ]
}
