{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "route",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.1-beta-plain.jar",
          "url": "route-1.0.1-beta-plain.jar",
          "size": 19313,
          "sha512": "9254d303866b111510b7f2deddc7fc82348d445c3fda39f56f88055682752ec66db82405c7b19c07946c6b984101ff72aa9229813098dcda340cb1223a3b82d6",
          "sha256": "754410f0b28c1688e7f575ef6b7cf95c44e7251e4e474cdc5724d857ad3b3672",
          "sha1": "8a419e3aacb67cd3a2f9a4fb1fe72c8152c5a65d",
          "md5": "fcaa7f10ee7f1f62e0f810416295ecaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.1-beta-plain.jar",
          "url": "route-1.0.1-beta-plain.jar",
          "size": 19313,
          "sha512": "9254d303866b111510b7f2deddc7fc82348d445c3fda39f56f88055682752ec66db82405c7b19c07946c6b984101ff72aa9229813098dcda340cb1223a3b82d6",
          "sha256": "754410f0b28c1688e7f575ef6b7cf95c44e7251e4e474cdc5724d857ad3b3672",
          "sha1": "8a419e3aacb67cd3a2f9a4fb1fe72c8152c5a65d",
          "md5": "fcaa7f10ee7f1f62e0f810416295ecaa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.1-beta-javadoc.jar",
          "url": "route-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "1e057d1986c50e9ad6c819f70812bfca53b5d3e53af80ff66d6a572635d2421db301f34feedff39a13654e14fe42c8181c0a3aad97f75109b264b52c3ae6396e",
          "sha256": "e81d990e5584fcff6b520e82f89165140f907d2c6229345e58a194c90a0f2b19",
          "sha1": "7b518c30ce3f6faa492e2b1b1784df6372b4a8f2",
          "md5": "b99afbacf0e2c8b02c2792f6a7ad1efb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.1-beta-sources.jar",
          "url": "route-1.0.1-beta-sources.jar",
          "size": 13582,
          "sha512": "18b6e867373ba30739c1319d029a787a881f4ac5bdb1a85b71f1a33510f2c09c62ddfd2a8ef11c07b603a827731e3d13afd9c0b6eed2382d5205c3a3d9574694",
          "sha256": "09dc89ad0eb30b22ac4f1fb0d436cd9887c66c3c4bed4f9fb375a104bb15de11",
          "sha1": "95ecbe2a90c472c8a76487da7184ba033860b40b",
          "md5": "2d546848a45c48d432b8763774ec7003"
        }
      ]
    }
  ]
}
