{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.3-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.3-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.3-beta-plain.jar",
          "url": "database-backup-1.0.3-beta-plain.jar",
          "size": 22740,
          "sha512": "0ebabb3fd24c74585fb9395e08f07844ebdd8948e9cd0f70f2c81d03b3b5735ff7916c91379443e3c111ac4677c02fcf2155a0c5b2f0e95ef0ff32847429f53a",
          "sha256": "ba9382f17700846aa1ba725f5f7ff32fd623532af1b6a0b5bb0b80c1a8e8f180",
          "sha1": "571ff69e1fbab61a59b5dc853254cf5133539259",
          "md5": "d1d4160176573753973bf166927baaa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.3-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.3-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.3-beta-plain.jar",
          "url": "database-backup-1.0.3-beta-plain.jar",
          "size": 22740,
          "sha512": "0ebabb3fd24c74585fb9395e08f07844ebdd8948e9cd0f70f2c81d03b3b5735ff7916c91379443e3c111ac4677c02fcf2155a0c5b2f0e95ef0ff32847429f53a",
          "sha256": "ba9382f17700846aa1ba725f5f7ff32fd623532af1b6a0b5bb0b80c1a8e8f180",
          "sha1": "571ff69e1fbab61a59b5dc853254cf5133539259",
          "md5": "d1d4160176573753973bf166927baaa6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.3-beta-javadoc.jar",
          "url": "database-backup-1.0.3-beta-javadoc.jar",
          "size": 261,
          "sha512": "593ddd5d0a5b589d865bca0266f67170c1343f2a86611e07282e981df516eb1d0469acbb3ad9ce1d24430fa463629c76f402e727fdbf1d2210083c0c8448d2b7",
          "sha256": "2a27160bf85889c54b223af55c02a92c05473e1b7b039bf5c8456e6a8e869f3e",
          "sha1": "69f3b02b9a176392efe2e8f38a9fe6035f274215",
          "md5": "7c4445075a99da1be69af4f5d3aa2163"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.3-beta-sources.jar",
          "url": "database-backup-1.0.3-beta-sources.jar",
          "size": 14674,
          "sha512": "c39ede3bb88ded40ecf12e1d6afc5ff33a54f2875f443006b30b33d701569f4410b8c27582e191659291d6f67e451840f484c1c8f7c5f284de9bfdc5906c80dd",
          "sha256": "eba731d9dd9cdbefb99d215c166fca4ae63cd6058fdf3b414fada518e7fbc2f7",
          "sha1": "bbc3f7a833482ecf164321f57c8e455f7278889a",
          "md5": "a21b6cc156451a90811f8adfd2e0110d"
        }
      ]
    }
  ]
}
