{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46771,
          "sha512": "2fa7a4832d75767ffbf9e4784bffd5e0b22e533d1b4f09c1ef60ee4e43cf8653594ff014f6e8a73eb73be4137a57f33d16f4a2fc88dbc5ee84a88f7ca6cdf12b",
          "sha256": "6083e262484f2400f7fa434a9de9b665c1f93d677440ed082d9cf0c957864b5c",
          "sha1": "4e120057aaf9e7dab62799bdebbc844bade805a2",
          "md5": "cc580faffe4ab87d238b8ccd3d5a8a6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46771,
          "sha512": "2fa7a4832d75767ffbf9e4784bffd5e0b22e533d1b4f09c1ef60ee4e43cf8653594ff014f6e8a73eb73be4137a57f33d16f4a2fc88dbc5ee84a88f7ca6cdf12b",
          "sha256": "6083e262484f2400f7fa434a9de9b665c1f93d677440ed082d9cf0c957864b5c",
          "sha1": "4e120057aaf9e7dab62799bdebbc844bade805a2",
          "md5": "cc580faffe4ab87d238b8ccd3d5a8a6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-javadoc.jar",
          "url": "common-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "06096a774cabb840fa8dc581eeec21bda372c7df748ec42475ec8e758a0d31779c2cbea45d4818c33fdf6299736d6fa8424bfbe948606f3ffe80665371e01bc8",
          "sha256": "aceab66e5b204fabaa4dcc6ace432a339770c7142f69ed86246477162062f1bd",
          "sha1": "97cf48c0a8b89db3ad52e1e55b0c4adede61ccb5",
          "md5": "e23fb731ca9dbdb23ac4eefea4f81f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-sources.jar",
          "url": "common-1.0.1-beta-sources.jar",
          "size": 26132,
          "sha512": "01760f8a31e65f2735f68441f535ff04167cccb64ad1be91d75d029f7d6411a4a8a524256d80e0c04b0f22cdd983107ed093c3fefaeeff4f43091b883f6d1328",
          "sha256": "672787f4e3eabe7c7fe3d0b3a3d53d700291b92adda9616605a387ed46d350d1",
          "sha1": "f97e0bfd1d4e93103c66c7bec98b46717bcbe5d3",
          "md5": "eb947bbd42e43f9a6c68f9858c468553"
        }
      ]
    }
  ]
}
