{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46730,
          "sha512": "cda3ca16261dae1ba338c11adf9b37884fac71a24cd581e5c0ba4d9c51270e9a33e2d8c5769fd15d93415a0720ade4307910bb22b37a8ae72b4f4f84401d363e",
          "sha256": "9433714bb560575cc275cf695ae1ef89149019bd1f6dbd1a968b43f9119a5c9e",
          "sha1": "2e478b169ce033a6d112cfecdf70ad12da586ee4",
          "md5": "8bf3c3476256977ecd757d4db43770a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46730,
          "sha512": "cda3ca16261dae1ba338c11adf9b37884fac71a24cd581e5c0ba4d9c51270e9a33e2d8c5769fd15d93415a0720ade4307910bb22b37a8ae72b4f4f84401d363e",
          "sha256": "9433714bb560575cc275cf695ae1ef89149019bd1f6dbd1a968b43f9119a5c9e",
          "sha1": "2e478b169ce033a6d112cfecdf70ad12da586ee4",
          "md5": "8bf3c3476256977ecd757d4db43770a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-javadoc.jar",
          "url": "common-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "624826e5ec3e0981b6690c4f6d2a235890ae0c19683c4ca34583a01bea8827780758b0f216464674d2e3d31f17a4f3a9e0fd99abf9e6de0e2df0b33af0be5cfb",
          "sha256": "dd22ac69d7688e8952af801f4e3421d1eecbada247d166386330780f6e7068c2",
          "sha1": "1c9973fc85d2de73b7ce7f99947753b724543ba5",
          "md5": "74c1dc4b42bdfc45e0a59149a3ca5ea1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-sources.jar",
          "url": "common-1.0.1-beta-sources.jar",
          "size": 26039,
          "sha512": "fcd3d76de60805889853ff21edb3125167c3b0480f315a664cd05722acb38df65624846ce6970e125caf3b77f6c6a09d3d3674369ba8b4d01aeece91e6866551",
          "sha256": "d00b3e59a7b3f8335f615911cdc3fa77db1ee7e431b5b08bd9efb9b5f3b1c49f",
          "sha1": "c80164ece3ecbc526410888fadc74228cb8b2dea",
          "md5": "7a869859597080e9376164f65750b36e"
        }
      ]
    }
  ]
}
