{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46730,
          "sha512": "e0756dd9d6c53072776dfc4c94514f0f0674d677707c5ccdb4e6161b57432cd6a2c23bac4198fa22fa7d2669074e93199c2ebe7f5ff677094e68ba6419495db6",
          "sha256": "9b95773f642a1e2a33ca5ca3c9fc1c22fcf27399936af2f236768cd42f0cb776",
          "sha1": "d8781e97b60368a4903365c0a0230dc67fa40963",
          "md5": "729880d43bc61f07ccb2d411386a8782"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.1-beta-plain.jar",
          "url": "common-1.0.1-beta-plain.jar",
          "size": 46730,
          "sha512": "e0756dd9d6c53072776dfc4c94514f0f0674d677707c5ccdb4e6161b57432cd6a2c23bac4198fa22fa7d2669074e93199c2ebe7f5ff677094e68ba6419495db6",
          "sha256": "9b95773f642a1e2a33ca5ca3c9fc1c22fcf27399936af2f236768cd42f0cb776",
          "sha1": "d8781e97b60368a4903365c0a0230dc67fa40963",
          "md5": "729880d43bc61f07ccb2d411386a8782"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-javadoc.jar",
          "url": "common-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "06096a774cabb840fa8dc581eeec21bda372c7df748ec42475ec8e758a0d31779c2cbea45d4818c33fdf6299736d6fa8424bfbe948606f3ffe80665371e01bc8",
          "sha256": "aceab66e5b204fabaa4dcc6ace432a339770c7142f69ed86246477162062f1bd",
          "sha1": "97cf48c0a8b89db3ad52e1e55b0c4adede61ccb5",
          "md5": "e23fb731ca9dbdb23ac4eefea4f81f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1-beta-sources.jar",
          "url": "common-1.0.1-beta-sources.jar",
          "size": 26039,
          "sha512": "2a8f80ce983e29f005217ace43b020d319c3108fd009416280b87d7b143d6836402d01498891ed5330327b57b49bda73f71f1c528705c2783f066a776773390f",
          "sha256": "b1dbc3c2c7ea7c2b3557c7de3271ad2ac6f5c3ce82a95b0d18c1913a2ab45821",
          "sha1": "e3e780ab773fb8421487a767950456267549660e",
          "md5": "e83c6900f21e44ab185eb97329f515f6"
        }
      ]
    }
  ]
}
