{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 74302,
          "sha512": "59ed0ed0b87d719063c287f5e0247bcf9896c2abf6e2874329f1c895ef8cb85330ad4a9c1a20f8241f3c9fba7cf6e9bd910f2874b27c897d4854dc578f692287",
          "sha256": "6b83eae61f67be5abc3380fc4a8b915672df41b6b2b8807e44e7a41da1cf51ad",
          "sha1": "9ac2a0eac290b4b7a7d8794b0e60eaa91a01502f",
          "md5": "84ce2209b12c9f43511bc471f7572642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 74302,
          "sha512": "59ed0ed0b87d719063c287f5e0247bcf9896c2abf6e2874329f1c895ef8cb85330ad4a9c1a20f8241f3c9fba7cf6e9bd910f2874b27c897d4854dc578f692287",
          "sha256": "6b83eae61f67be5abc3380fc4a8b915672df41b6b2b8807e44e7a41da1cf51ad",
          "sha1": "9ac2a0eac290b4b7a7d8794b0e60eaa91a01502f",
          "md5": "84ce2209b12c9f43511bc471f7572642"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-javadoc.jar",
          "url": "common-1.0.0-javadoc.jar",
          "size": 370687,
          "sha512": "87eaea534c86812f742a0dd32fbcbd0aa6436652e85fb693c90f0600a2dde8e396473cb52ecd5f1b1370f3b05f1f7bb9c502b2788cf5f1b971fa8a0ba4bf6e56",
          "sha256": "120a2bfd007b201e7c5b200f7815d225f3138ae8ae15247ef03854b9bcd8a3b2",
          "sha1": "2eeec0051371d4d2c74465f1ab4d5d1850159b25",
          "md5": "33f7867c38e39d2266210b41cef5c5af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-sources.jar",
          "url": "common-1.0.0-sources.jar",
          "size": 44576,
          "sha512": "a1620d4e9491c157ed521762fc060948bc00e66b3cf7b04da8c283f94ba0518c3a02ba4f3fe844ae4c6aec293a3e9ce8f6987f5c4db006cdc0d4ad24b3dc08c7",
          "sha256": "a68e8fcd165a387ebbd8ca830ddc2409adc24ca227f78e183f42a81822593479",
          "sha1": "59b8d421a6719b1e39810052d18c06ad6537d6bd",
          "md5": "f272dbf258138de38a6d47c9140f2524"
        }
      ]
    }
  ]
}
