{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.2-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "aliyun",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.2-beta-plain.jar",
          "url": "security-1.0.2-beta-plain.jar",
          "size": 153573,
          "sha512": "9cfe4d747991e7c44e37705320b2c48b9dc0745565ac61f4fc2476d45bcb1b0b88e6148307fd48a5feee656c2a5a5fd1a1537b1b491ddcd4b33ac0534a7cc952",
          "sha256": "5381923ccd4f6fb07fa77fbf053433a34f9f4d7e78947dda686222b1ea74527b",
          "sha1": "d81dbe07ded5c915fbe4f4fc273117269f97ac0c",
          "md5": "cd728c126daaddb5791621ead3e32ae8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "aliyun",
          "version": {
            "requires": "1.0.2-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.2-beta-plain.jar",
          "url": "security-1.0.2-beta-plain.jar",
          "size": 153573,
          "sha512": "9cfe4d747991e7c44e37705320b2c48b9dc0745565ac61f4fc2476d45bcb1b0b88e6148307fd48a5feee656c2a5a5fd1a1537b1b491ddcd4b33ac0534a7cc952",
          "sha256": "5381923ccd4f6fb07fa77fbf053433a34f9f4d7e78947dda686222b1ea74527b",
          "sha1": "d81dbe07ded5c915fbe4f4fc273117269f97ac0c",
          "md5": "cd728c126daaddb5791621ead3e32ae8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.2-beta-javadoc.jar",
          "url": "security-1.0.2-beta-javadoc.jar",
          "size": 261,
          "sha512": "3242975453f89105a99c7608501593db49d62b83b51940272d72eb594c89a4cd373d9068c8d4048a923ff57da58252651fcbc5e483a6b6940081f7883601047e",
          "sha256": "cc7ae9a34775f5faba21e588b5a2b06a535174ae7098cbacdae29a3ae25e404f",
          "sha1": "54ed3b3a8ec60d9865b8d8b249ff37f14aa3b0a4",
          "md5": "9005d5be55721c3f542d918a1f5c42ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.2-beta-sources.jar",
          "url": "security-1.0.2-beta-sources.jar",
          "size": 98132,
          "sha512": "21e9e18cd42a1a658862bc18fc92b0932966bff422bb9ff70ac2dc5e4d94ca0d48f6e198a70b9eb2fc137dab65a546e8a9630a6507a7cbb39261e15645e86cc5",
          "sha256": "a4ff5597a581253fad2a095fa380c9859964ba34bc9a9b3f44452ce443a4bc9b",
          "sha1": "4ba049107e022a3947a5613e2fafe7ff00f84def",
          "md5": "01f8ea3d89efd2d895afb3794d55c071"
        }
      ]
    }
  ]
}
