{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 15060,
          "sha512": "3d874b0fdc8bab4db3a0472ba6a47eb8fa54ab71c165e0669790748d1c88a95774628b149cfb95df1420f10ad1dc2fe093ad1481df91eee79a1c3267fe1408ca",
          "sha256": "4d84fc432ba559ad82eb3aa5dedd5abdd3400d9dcf6e49f661162a38387460a8",
          "sha1": "ef8fe3caee1b8cfee8b9453e9755323f6be612d2",
          "md5": "275efd57b263f9aa81d08540746aa14a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 15060,
          "sha512": "3d874b0fdc8bab4db3a0472ba6a47eb8fa54ab71c165e0669790748d1c88a95774628b149cfb95df1420f10ad1dc2fe093ad1481df91eee79a1c3267fe1408ca",
          "sha256": "4d84fc432ba559ad82eb3aa5dedd5abdd3400d9dcf6e49f661162a38387460a8",
          "sha1": "ef8fe3caee1b8cfee8b9453e9755323f6be612d2",
          "md5": "275efd57b263f9aa81d08540746aa14a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-javadoc.jar",
          "url": "jackson-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "de1788d78db1751701fb3735fb675483a55b7ce0936967bd1d4cbd7b88b24d59e770b77e96516987d37310f2e34d396b952c4023d5db9b8495667333357b9735",
          "sha256": "7525b7f1bf6169d09a9dcb79d578a21ea10bb2274b4ad9f4cf77db33dc5aaeb6",
          "sha1": "6c6a41f487d814f55f77a24f763b9aa3ba2b5ca4",
          "md5": "cc657b915d5743580ce8839ecd979638"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-sources.jar",
          "url": "jackson-1.0.0-sources.jar",
          "size": 9156,
          "sha512": "48a5c7a5665ca74cf47d025b7a91431a2dccf74c7fa2395bc2690cb1bc99998ed402c6bad1b3d251955c168b425c257e9853aafb7a8ff7afdebe7509eace1f68",
          "sha256": "213073dd4e1b8570f7557778b88061202f38c17e71da3f2d5ac78eb9123c1ab9",
          "sha1": "6aea985d131986c11cca51096780674ec34341d1",
          "md5": "29c3140c7cfbf372c2d3645680f4a292"
        }
      ]
    }
  ]
}
