{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 14165,
          "sha512": "4ccec0e0c33114adde4957999c88b9b76931b0795b08af6549c0e8b8bd441dbcbcd1c22185cd51647b25d86a3ad1111decc8122221c27f08cdf46b2e32382742",
          "sha256": "63e7a76fb6c67b8088be46ede963a65c144c40ba47883a2b5a63204f5743b816",
          "sha1": "2475ed1a22d51d648f86c379841c41e9da5d6408",
          "md5": "cb067ccd9ca06958cb7ecf41211bf997"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 14165,
          "sha512": "4ccec0e0c33114adde4957999c88b9b76931b0795b08af6549c0e8b8bd441dbcbcd1c22185cd51647b25d86a3ad1111decc8122221c27f08cdf46b2e32382742",
          "sha256": "63e7a76fb6c67b8088be46ede963a65c144c40ba47883a2b5a63204f5743b816",
          "sha1": "2475ed1a22d51d648f86c379841c41e9da5d6408",
          "md5": "cb067ccd9ca06958cb7ecf41211bf997"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-javadoc.jar",
          "url": "jackson-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "0785e30487bf0f972115fc2da646a428c5e97248a43f06bc1cf1b7714dd0d6f4fd2b5a7408685e722c96a496a5dd07aeb279aae57c719d3fac42f6718207436f",
          "sha256": "72cff99ca59335ee6ec178c298a3478851fe1ec4ac97b15fe2feedb77fe9df0d",
          "sha1": "c01a9260b2316734ccc0d1437da8b490f8a3355f",
          "md5": "71a0bd5cc8f6df00d6a8639ffa9c9d34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-sources.jar",
          "url": "jackson-1.0.0-sources.jar",
          "size": 8573,
          "sha512": "933b41e0e4ef43a25bfa0129c271b0bf15cbf62f227a55814432742f82203472c073de3b99e3a69cc926bb1524067072efda499f0485b9667309787b812d75e1",
          "sha256": "35a3c9f204699f776e1db68dfb8c0787dab873902bf196d1bf6a55763217d7f0",
          "sha1": "067ac12da4e53c271922be5c7fc5b18e5630f607",
          "md5": "f924f889d8e09b04c7d6739915d18515"
        }
      ]
    }
  ]
}
