{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "jackson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 15117,
          "sha512": "9d8e8cdfd45951dafd9bd3e03b48244fe75baa66a958d6145e4e3cd1a868676c9277dc22e868999328e7511dd41c043eeaa55107446e4c404ba7d886890ca188",
          "sha256": "ff8ebacc47195fc67f23fb101cf81032adeb832a9ec564f531fe4709b19e3966",
          "sha1": "ad3e1e3b1391361f2b675d0f27d5ce6dd2b37846",
          "md5": "7cc8052323cc0b8d9669e3cbcec699c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "jackson-1.0.0-plain.jar",
          "url": "jackson-1.0.0-plain.jar",
          "size": 15117,
          "sha512": "9d8e8cdfd45951dafd9bd3e03b48244fe75baa66a958d6145e4e3cd1a868676c9277dc22e868999328e7511dd41c043eeaa55107446e4c404ba7d886890ca188",
          "sha256": "ff8ebacc47195fc67f23fb101cf81032adeb832a9ec564f531fe4709b19e3966",
          "sha1": "ad3e1e3b1391361f2b675d0f27d5ce6dd2b37846",
          "md5": "7cc8052323cc0b8d9669e3cbcec699c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-javadoc.jar",
          "url": "jackson-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "de1788d78db1751701fb3735fb675483a55b7ce0936967bd1d4cbd7b88b24d59e770b77e96516987d37310f2e34d396b952c4023d5db9b8495667333357b9735",
          "sha256": "7525b7f1bf6169d09a9dcb79d578a21ea10bb2274b4ad9f4cf77db33dc5aaeb6",
          "sha1": "6c6a41f487d814f55f77a24f763b9aa3ba2b5ca4",
          "md5": "cc657b915d5743580ce8839ecd979638"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jackson-1.0.0-sources.jar",
          "url": "jackson-1.0.0-sources.jar",
          "size": 9190,
          "sha512": "b10e3872afd4eb2f095702b6dc9d5d59db21022c2893e9a6b7b05006165aefac0c3767d82137c0523a4132d65c6656ad49dae6cd9c624924d2947110253a33fd",
          "sha256": "63a5376400369b7e05900391abf5e5ee802cfa05488d19fc09b378d0b821886b",
          "sha1": "63f9d01c3db15aabf04c427c6489fa2724ca27bb",
          "md5": "84e727f9d24288cad834b8a189eb614d"
        }
      ]
    }
  ]
}
