{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "5ce796e79ba97bcf45b3fb6983c2d4ef0c7886bcbde08f176b69c5e097e5c5cd34790a8ea530fc7ce0ebde4b8588901ed525f734fefb13955968b96605184bd5",
          "sha256": "2bfd13121545da17965a512d2dffcac37c8f813b69d28e8d0353e493022bc1ac",
          "sha1": "7f02ef4d8610dc4f97b24c64fdb74ea481db9e4f",
          "md5": "c56c0eef8202c2bba700dfb3bae81af1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "5ce796e79ba97bcf45b3fb6983c2d4ef0c7886bcbde08f176b69c5e097e5c5cd34790a8ea530fc7ce0ebde4b8588901ed525f734fefb13955968b96605184bd5",
          "sha256": "2bfd13121545da17965a512d2dffcac37c8f813b69d28e8d0353e493022bc1ac",
          "sha1": "7f02ef4d8610dc4f97b24c64fdb74ea481db9e4f",
          "md5": "c56c0eef8202c2bba700dfb3bae81af1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-javadoc.jar",
          "url": "database-backup-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "7ca640ef0cd1e493242ceb97ba0133bc687d68bd40dec7ca27eada9dceff15a68c6e58da574d14d5e069c05dec6003d68bab000f08437028926d5fc8404d6e26",
          "sha256": "df6df0939115a679dcfe2a018715f6116ebef6bb42987d3034c7f8227acf828c",
          "sha1": "14a607bd8c18c8021e01c47122a5dad0f163a762",
          "md5": "0f9ebeabb8c453d5be4c4c455341fdbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-sources.jar",
          "url": "database-backup-1.0.1-beta-sources.jar",
          "size": 14674,
          "sha512": "787ab00f1847da39952ecaa9e3ed9df22d10ba8feced29e712490935bf29d0c9eadd13a0a848a89183a432eeda2c0fc7b939aae89d2aee621c0261a59418ed80",
          "sha256": "0c257a8bbc43977c6579e7c12070aac00e45f0fa34484eaa5633e7a66975cba9",
          "sha1": "2212e08103af6e10768b3fa4cede22c503a459ac",
          "md5": "96299de9ff86996da6b222486fbd93a6"
        }
      ]
    }
  ]
}
