{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "a97c6c0aa8428118f1feb707d49d1d9feb90621415f212769db728a038e6c926ee861137650bc3f1e0f943fa9b1209e99e06da1380eaa7e8393dd07a03469f74",
          "sha256": "898f1025a25b06a408223ce185914fe2ac389c097e4dfc447bf5490b83ab01e6",
          "sha1": "b780d37b8cf63d4e827eec680d36828b462b2aca",
          "md5": "f780f7d717e21727c1d141d86649f8c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "a97c6c0aa8428118f1feb707d49d1d9feb90621415f212769db728a038e6c926ee861137650bc3f1e0f943fa9b1209e99e06da1380eaa7e8393dd07a03469f74",
          "sha256": "898f1025a25b06a408223ce185914fe2ac389c097e4dfc447bf5490b83ab01e6",
          "sha1": "b780d37b8cf63d4e827eec680d36828b462b2aca",
          "md5": "f780f7d717e21727c1d141d86649f8c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-javadoc.jar",
          "url": "database-backup-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "343785c0b13d680e9b1a14c5019cfc9be00e283f8ae4d00cdc552df85e7103a3552ea42b90e8d0c553d9a4be4e59e11729f6caae5f17bbe9bfb58b835cdac0b4",
          "sha256": "05ab276d4761fc9bfc000454f0e549d87d1f7f2f42a45e38a099f2dffc3f767d",
          "sha1": "9d10fc25292d1053623fd966b60f3dba1fa41004",
          "md5": "f8b6516c053d2a54fb35fcdb6fd6ffc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-sources.jar",
          "url": "database-backup-1.0.1-beta-sources.jar",
          "size": 14674,
          "sha512": "18aa629ccd31ce78a618bd195a14b042d16412cd5040a55a0da722f6acaf24791d20925141c70ebed62fb2d7efc81e90d085843d265235429a28be338ce62e99",
          "sha256": "fef5e9f24455245bff3d0076f4a23fe63f1c887094f4ced0f1bca5d4db62fa1b",
          "sha1": "7cba1d0c3ad3debd6bae39c02db05cff018d189c",
          "md5": "91bdf6328ee7626f274e2e4faf5ac872"
        }
      ]
    }
  ]
}
