{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "74c61f5c52fcbc8005697bd3459748672861701ed63574a14b24fb1832606293261bef9d7f7bcb47a3583fce10252af1f8c4569617d88ea7540e715614215a1d",
          "sha256": "2f08b3aab3858a0216d2595ab5d4bc16e52abef0cabcf3bee5c83f1b20777324",
          "sha1": "6d51a610b85562215684f1ecb8be20c510991468",
          "md5": "1a3b7990ac9f5ac58728fcd574fe513b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.1-beta-plain.jar",
          "url": "database-backup-1.0.1-beta-plain.jar",
          "size": 22740,
          "sha512": "74c61f5c52fcbc8005697bd3459748672861701ed63574a14b24fb1832606293261bef9d7f7bcb47a3583fce10252af1f8c4569617d88ea7540e715614215a1d",
          "sha256": "2f08b3aab3858a0216d2595ab5d4bc16e52abef0cabcf3bee5c83f1b20777324",
          "sha1": "6d51a610b85562215684f1ecb8be20c510991468",
          "md5": "1a3b7990ac9f5ac58728fcd574fe513b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-javadoc.jar",
          "url": "database-backup-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "1f92419ddc1fa2d02d6711ea30b3ad19ab7c3d1a2c0f9534289341b0c9895d6033a462cb8a67ac70370591f4a3c6e453569a4bf9434517f520a1b7d5556b76c8",
          "sha256": "141307b090fe1c7daee3d520d3fc22ec98b90225332fd88d1b4c3d0aa6e3875a",
          "sha1": "66f23c3bdbe52d9e89ed954e7ee9e461ebc411c9",
          "md5": "03abdffa4f785b59ef1100c7976c608a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.1-beta-sources.jar",
          "url": "database-backup-1.0.1-beta-sources.jar",
          "size": 14674,
          "sha512": "b93b0f0af28b4d1fcddbf6d602bfd090633b9c87841408fb63932f86f1d28f16313b6d0ab66d8ee95a19f10bde00cfe11e0dafc30044ed6fbdd145bcb74c0364",
          "sha256": "0402883156a6f2861b9b7b3f429a3e3e36b51d622f1e4fee25ebbf78f59c6c08",
          "sha1": "1f1a3856f3f7cbefea3280682fac3fd66c267e3e",
          "md5": "7ebe70439c1a7fbd8812c077ce54c6f3"
        }
      ]
    }
  ]
}
