{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41896,
          "sha512": "3403efcf6a742380b122bb43aeb03d05ac3b758ed3aa4deeff756a804ef1064b3cea91a5495166719404c88831e9f76d21fd90c0847d067e98bcff7e8f50e9d3",
          "sha256": "3c0190929f8885e3bc5292f45574642f6b75adb07aa8c234fb9f244af924bf10",
          "sha1": "395fd82e09075c6101d92a19f888f4fc07f86b7b",
          "md5": "73515d3f3a3cb7d70e224549b0798adc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41896,
          "sha512": "3403efcf6a742380b122bb43aeb03d05ac3b758ed3aa4deeff756a804ef1064b3cea91a5495166719404c88831e9f76d21fd90c0847d067e98bcff7e8f50e9d3",
          "sha256": "3c0190929f8885e3bc5292f45574642f6b75adb07aa8c234fb9f244af924bf10",
          "sha1": "395fd82e09075c6101d92a19f888f4fc07f86b7b",
          "md5": "73515d3f3a3cb7d70e224549b0798adc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-javadoc.jar",
          "url": "operation-log-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-sources.jar",
          "url": "operation-log-1.0.0-sources.jar",
          "size": 27958,
          "sha512": "6e1a435282fb3adbcf57e7a51c8b84acd608b8c3e4f032046b6f34d2eb03cd3b711f3c467c1bb7f0930ebab92d10981326beee0653e6c623c4a1f21c83dcef6e",
          "sha256": "65d4a559fd1e8609e40cd7b71f892c6e931c24fe7f43f7119abb989da5539e97",
          "sha1": "9b9ce11a09f3db642309742e65874588c37f1278",
          "md5": "d90a9f10cd3c238c41267ff3523e53cc"
        }
      ]
    }
  ]
}
