{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41896,
          "sha512": "ed1132754d5614fe9505869a8021acd6f300d8e9e5a30a3a09d67f7995764502cae8bd800e4b7bd5b1f51679af49b68ad1f3c2fb38986d5b0d15c1dea78bf942",
          "sha256": "ceb3315a6e6b66501c98f94e640c886c25071c711543c76bd03aa1dd54c35636",
          "sha1": "810695eba21c4f5f7963f7315552873a56dbbc96",
          "md5": "9e49ed169f4cab18852bf3d514ad9122"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41896,
          "sha512": "ed1132754d5614fe9505869a8021acd6f300d8e9e5a30a3a09d67f7995764502cae8bd800e4b7bd5b1f51679af49b68ad1f3c2fb38986d5b0d15c1dea78bf942",
          "sha256": "ceb3315a6e6b66501c98f94e640c886c25071c711543c76bd03aa1dd54c35636",
          "sha1": "810695eba21c4f5f7963f7315552873a56dbbc96",
          "md5": "9e49ed169f4cab18852bf3d514ad9122"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-javadoc.jar",
          "url": "operation-log-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "54bee51f5d9ff7631f4c326058301423cbcfdf146fd527abd3a0a18d0fdeaced2c208e4611e3f2ac23151756618b16fb280bebdcfb20be7e5fd86982f2411895",
          "sha256": "fc1f42e99e0aa1e482b1e4f70efeaaf6df7255288faeb71bd98bdae4e2e669fc",
          "sha1": "6b1c3f66e1d3950316997281d3740d6aa2ddad03",
          "md5": "8035667fd57b1f7fbc8ec1082938a78f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-sources.jar",
          "url": "operation-log-1.0.0-sources.jar",
          "size": 27958,
          "sha512": "ece1c03fbb7ae73a2b07e8de8edfc7cb8f4400c7344ee0a5c0a3c7d8b1c8ae602ca2f7e3e80d4443ca21c720a6376268bd72a4458f7ddb22201e94ea69337784",
          "sha256": "c1398fd81bd69f67d33aaf8d86a520cb2deedbf279517042d4bcd124c65b16eb",
          "sha1": "5f2a156bae0248e0f6eab54341264143cce83696",
          "md5": "ff50bde5ed877848df14827b8e97a0d2"
        }
      ]
    }
  ]
}
