{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41749,
          "sha512": "e8ac916349a89e1540acf3dc2f922b6893d79bd87d64561e5781f01e99c9a31bc040d399a8bf10bd2472809f69fdeda1656ce5706c96ae44fd5c3aa191e6c381",
          "sha256": "dea360fbb619388c2787952de2b03c11f4fb6cb57aed079ac5b12c251e8f741b",
          "sha1": "65ebc127111b1af0f5d2df15c884ce5e886bee70",
          "md5": "30ead79733120a61b038118d1d25e843"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.0-plain.jar",
          "url": "operation-log-1.0.0-plain.jar",
          "size": 41749,
          "sha512": "e8ac916349a89e1540acf3dc2f922b6893d79bd87d64561e5781f01e99c9a31bc040d399a8bf10bd2472809f69fdeda1656ce5706c96ae44fd5c3aa191e6c381",
          "sha256": "dea360fbb619388c2787952de2b03c11f4fb6cb57aed079ac5b12c251e8f741b",
          "sha1": "65ebc127111b1af0f5d2df15c884ce5e886bee70",
          "md5": "30ead79733120a61b038118d1d25e843"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-javadoc.jar",
          "url": "operation-log-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.0-sources.jar",
          "url": "operation-log-1.0.0-sources.jar",
          "size": 27904,
          "sha512": "91b30eaa005ec89ea201df0151c90527881028efed91f488119dd2059cd866fdbe37b069262564c94b790338b9ad70092b83e8b1ea97be18684ef52c7be11504",
          "sha256": "70869c6dca2e9ff8d9f6f4f4885a8e87c52eabdf128cbd578fc51b4017d3336b",
          "sha1": "0c6d04beada6c172a593e6b8432d66d5db853298",
          "md5": "59fb4b3b29c314c5eb21fbdaa994966c"
        }
      ]
    }
  ]
}
