{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 46312,
          "sha512": "51bfe8ea7cff7d7d3484ae99c205d99aba7da62f412702500133f4af0b44062283db7df520d79c22faf7ad0138f644f15094eae598daf9356dccedd51c3a991c",
          "sha256": "be5863ece8da21a3e9f4e24d1a86ec71ff888283d524736298257eb473769845",
          "sha1": "50682fe2f9b09135a19eee1f6d7d9ba47c17821e",
          "md5": "b891e7b7c849ce03b3ca635ec9abccd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 46312,
          "sha512": "51bfe8ea7cff7d7d3484ae99c205d99aba7da62f412702500133f4af0b44062283db7df520d79c22faf7ad0138f644f15094eae598daf9356dccedd51c3a991c",
          "sha256": "be5863ece8da21a3e9f4e24d1a86ec71ff888283d524736298257eb473769845",
          "sha1": "50682fe2f9b09135a19eee1f6d7d9ba47c17821e",
          "md5": "b891e7b7c849ce03b3ca635ec9abccd1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-javadoc.jar",
          "url": "database-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "06096a774cabb840fa8dc581eeec21bda372c7df748ec42475ec8e758a0d31779c2cbea45d4818c33fdf6299736d6fa8424bfbe948606f3ffe80665371e01bc8",
          "sha256": "aceab66e5b204fabaa4dcc6ace432a339770c7142f69ed86246477162062f1bd",
          "sha1": "97cf48c0a8b89db3ad52e1e55b0c4adede61ccb5",
          "md5": "e23fb731ca9dbdb23ac4eefea4f81f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-sources.jar",
          "url": "database-1.0.1-beta-sources.jar",
          "size": 27070,
          "sha512": "091e575d820c550eab225bc6e0c61ca3dd7046e1b74968c0c5cef083b1613e662ee575c2c69dc69a135ecd04ef09a967ad23c9b2c62226d6de9bb45c48ca3aae",
          "sha256": "66e2320fbc1203f0bc07e9550ebd3383673ef665026bdbc3173f3bf4bade47ea",
          "sha1": "ac7bd5e9ab1318263d54fd27a84a57be6444e80e",
          "md5": "6652473aeef3778fd73e9df08ac8347d"
        }
      ]
    }
  ]
}
