{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 39323,
          "sha512": "63e8f21486568d256046b21ce7d42b9dab5421e800a26a80d57fe6f603ad567266777fda502b2a977587d01f44684260ac6228c68805fbf24b9cc1d00105e827",
          "sha256": "37cfbf621f1fa55ea1ed1d39543a5d8a94cfe39d0a810507cfc0292a3ab81ab2",
          "sha1": "9b9b746225e43e45324a2bcdc423fa75b67fd55e",
          "md5": "c6ffbeff6ec156b139d5307708eb15aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 39323,
          "sha512": "63e8f21486568d256046b21ce7d42b9dab5421e800a26a80d57fe6f603ad567266777fda502b2a977587d01f44684260ac6228c68805fbf24b9cc1d00105e827",
          "sha256": "37cfbf621f1fa55ea1ed1d39543a5d8a94cfe39d0a810507cfc0292a3ab81ab2",
          "sha1": "9b9b746225e43e45324a2bcdc423fa75b67fd55e",
          "md5": "c6ffbeff6ec156b139d5307708eb15aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-javadoc.jar",
          "url": "database-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "96d6f9c1f2d8afeccdec430ed69c9386e3858d3977b2830526f25a65a09a97bb9918959ae2d913409d454161c62fd26fb95bb6148e9540062f33591c8c0fff2b",
          "sha256": "8e4aab8ed835ebfe9ca60ba5233eb466dfd0e2469431a50e2737aa3713c274fe",
          "sha1": "f7d13cbb1b02d2a809bf7c0e5f0d464daf6c9712",
          "md5": "79d05e01e410c48a95a348a7b51d1df4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-sources.jar",
          "url": "database-1.0.1-beta-sources.jar",
          "size": 23369,
          "sha512": "b0add83c0ad48ca57de90b410f98296f373d1b4dfd6da94c1a8a3d263617168e9ca47c031fe9e7e2acd8e6cd6d61bd8d988436e6b808efa5d37f0957bca5aff4",
          "sha256": "b2a2cc99457ed1cefc6ef2e98a89b70df6ec902c2192d58a5b3e0eb351a7044e",
          "sha1": "799b69d3c0d6c8b012537dfaf582ca3544a32d52",
          "md5": "f0a0cf02a50fe73aaddd4875afeca062"
        }
      ]
    }
  ]
}
