{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 46308,
          "sha512": "eff910213635aa714749e4e7958c76a555346e8e03a8642fbac70e0990dc2c2b0e743fc9cc578557937e262ec5c0dd00a16f09512e3e07a70c6f6c605dadc38c",
          "sha256": "cc7ce1c2066a9dacebee859da655a6c2f015475a04d3a00e8710246adff03e6a",
          "sha1": "5e30c7f75982385f402936a3efad960978f57093",
          "md5": "1acfd01f193660ea6cf35b8822fc22ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.1-beta"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.1-beta-plain.jar",
          "url": "database-1.0.1-beta-plain.jar",
          "size": 46308,
          "sha512": "eff910213635aa714749e4e7958c76a555346e8e03a8642fbac70e0990dc2c2b0e743fc9cc578557937e262ec5c0dd00a16f09512e3e07a70c6f6c605dadc38c",
          "sha256": "cc7ce1c2066a9dacebee859da655a6c2f015475a04d3a00e8710246adff03e6a",
          "sha1": "5e30c7f75982385f402936a3efad960978f57093",
          "md5": "1acfd01f193660ea6cf35b8822fc22ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-javadoc.jar",
          "url": "database-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "06096a774cabb840fa8dc581eeec21bda372c7df748ec42475ec8e758a0d31779c2cbea45d4818c33fdf6299736d6fa8424bfbe948606f3ffe80665371e01bc8",
          "sha256": "aceab66e5b204fabaa4dcc6ace432a339770c7142f69ed86246477162062f1bd",
          "sha1": "97cf48c0a8b89db3ad52e1e55b0c4adede61ccb5",
          "md5": "e23fb731ca9dbdb23ac4eefea4f81f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.1-beta-sources.jar",
          "url": "database-1.0.1-beta-sources.jar",
          "size": 27009,
          "sha512": "67aae4951a7e0b134d05a0bbac40c8e617dfac7f76f2506726f3930f8a1091f0cb27fff8fae0bc2097c8df9190cf32e6d5e3f4bc09649e5795082769c6269baf",
          "sha256": "06bf8bcaa60db5cf31e9d85cff44d330ffe98431b57f263a87eaa4215bcc9d11",
          "sha1": "7122e1d180b36e8cf1c2840818e3acb60dbbfc7f",
          "md5": "69c2284a20321d8c86f1375907cf8041"
        }
      ]
    }
  ]
}
