{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "aliyun",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.aliyun",
          "module": "aliyun-java-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-1.0.1-beta-plain.jar",
          "url": "aliyun-1.0.1-beta-plain.jar",
          "size": 10698,
          "sha512": "833a56adf534bac451eefd10ba24a1f5a1b30964766e9575006eb9c85f9d05a5b1d16a5fe0a10c6bfb6c47d5a1620e55760d79721632239a58ed959d4ddf7cff",
          "sha256": "2b62ddc2b681ac8aa1752c864d4dce1d51ae8c2c8543160eae32d4e77e913ded",
          "sha1": "c2fd0cffef6ef915d8e9f8142cacd85d8ad4a5d0",
          "md5": "48fb1d8b478f69f88b6642a2ba64ffee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.aliyun",
          "module": "aliyun-java-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-1.0.1-beta-plain.jar",
          "url": "aliyun-1.0.1-beta-plain.jar",
          "size": 10698,
          "sha512": "833a56adf534bac451eefd10ba24a1f5a1b30964766e9575006eb9c85f9d05a5b1d16a5fe0a10c6bfb6c47d5a1620e55760d79721632239a58ed959d4ddf7cff",
          "sha256": "2b62ddc2b681ac8aa1752c864d4dce1d51ae8c2c8543160eae32d4e77e913ded",
          "sha1": "c2fd0cffef6ef915d8e9f8142cacd85d8ad4a5d0",
          "md5": "48fb1d8b478f69f88b6642a2ba64ffee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aliyun-1.0.1-beta-javadoc.jar",
          "url": "aliyun-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "124af4075e2b322d1c9894377fa161c6634898c239e261ac6d332afd52fd19ce3c4e2d631cacb06c125b65285cf39724971175052fc961e4789300011e47ed27",
          "sha256": "c1649873822bafdcbbc76b48ef0bf36e69cb6bf0db0426fdf56708ae2972ce5a",
          "sha1": "8f7bc5874ecf6c84da2b92552f08df244176f075",
          "md5": "48854b283975a294d1576d1d11de4e2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aliyun-1.0.1-beta-sources.jar",
          "url": "aliyun-1.0.1-beta-sources.jar",
          "size": 7523,
          "sha512": "8e6195b9471098959dcfa07437e66402d3c31181a4d6e1d73b53367d5201f4a66d5ac95fa5d945116f5badc1de0f04574f44ad0b71bda21c611c0a5a65596f20",
          "sha256": "15b7e3ae9fa5b1a9e23c1b1c7140c3d85a979d62f89c5df52bcb4eca723c4283",
          "sha1": "b6e0a9559595cfc7973f38100ec8f7c347d6f5fd",
          "md5": "10bd2ae0477b4265926a2cda2bb9df08"
        }
      ]
    }
  ]
}
