{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "aliyun",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.aliyun",
          "module": "aliyun-java-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-1.0.1-beta-plain.jar",
          "url": "aliyun-1.0.1-beta-plain.jar",
          "size": 10698,
          "sha512": "92de1c618b2413f144c5998a2e907792c6ffdc71e65a5bb56df8667ad13e6cd6d36ca069a0cc1bb1d82a11a21fc8fc5ebc7163983d42babb15106fe6171800f0",
          "sha256": "bae925fe30917a10d01d9f6a218239c00602a27d6814a6a82da268300e2f0377",
          "sha1": "a96258002442569678437429f7d19394408a5368",
          "md5": "5f50f6e8cf72df7490f5eb12aef7975c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "redis",
          "version": {
            "requires": "1.0.1-beta"
          }
        },
        {
          "group": "com.aliyun",
          "module": "aliyun-java-sdk-core",
          "version": {
            "requires": "4.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "aliyun-1.0.1-beta-plain.jar",
          "url": "aliyun-1.0.1-beta-plain.jar",
          "size": 10698,
          "sha512": "92de1c618b2413f144c5998a2e907792c6ffdc71e65a5bb56df8667ad13e6cd6d36ca069a0cc1bb1d82a11a21fc8fc5ebc7163983d42babb15106fe6171800f0",
          "sha256": "bae925fe30917a10d01d9f6a218239c00602a27d6814a6a82da268300e2f0377",
          "sha1": "a96258002442569678437429f7d19394408a5368",
          "md5": "5f50f6e8cf72df7490f5eb12aef7975c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aliyun-1.0.1-beta-javadoc.jar",
          "url": "aliyun-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "653a9ebc73be78126cebd2913843224e8d22e824010ac65f8484daebae652d699332f001229af72adb4a83af3e689e7020d6e0b73b4ac72da5ed1b7d233e5ccd",
          "sha256": "39a4194a8e57fa43881d054dadd28d6ce05a44ab921c26b7db7fa9244144d293",
          "sha1": "6d431f7fbfc3e2d61a06f2eb4fd4e39a540261ec",
          "md5": "e5513372e358578e74811888ca32f9dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aliyun-1.0.1-beta-sources.jar",
          "url": "aliyun-1.0.1-beta-sources.jar",
          "size": 7523,
          "sha512": "ec0a3eb60927b9bfc9d2dcabdd4a6059ffb8d2039bc693421e6359c6b38058d7fcaab86bd5e88e7850db9ea3cc864887ffe48e9f9e4f3b3d58585d4faf263368",
          "sha256": "beeaff20e6c236c3b2335032fc789e447a0bbcd6baf97b9813a3e55e4d5472b9",
          "sha1": "478604a18f720119d7921ecf054f08d5341869c9",
          "md5": "5fbeb9b58351190f0ddc767e5ad7b95f"
        }
      ]
    }
  ]
}
