{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46250,
          "sha512": "1bc1daa10da7a3e9d8db0f387269f985d963ba87c5963ff99f204d829ab84e887cf1df2296ed74006c2ad7322cb732976b559ad770f64ac67fc1272f28888eab",
          "sha256": "82a933fec6b73188029de284dddb198ab1e471ab30a5dd879fed08b9adfa3e40",
          "sha1": "9d4c1b0261c835596158bc753e54aaf58edbdd61",
          "md5": "a37d8a8f383065806ec8a15ecedddfa3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46250,
          "sha512": "1bc1daa10da7a3e9d8db0f387269f985d963ba87c5963ff99f204d829ab84e887cf1df2296ed74006c2ad7322cb732976b559ad770f64ac67fc1272f28888eab",
          "sha256": "82a933fec6b73188029de284dddb198ab1e471ab30a5dd879fed08b9adfa3e40",
          "sha1": "9d4c1b0261c835596158bc753e54aaf58edbdd61",
          "md5": "a37d8a8f383065806ec8a15ecedddfa3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-javadoc.jar",
          "url": "database-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "4248ce0e50489f88a5013601bf27d83a498546f60bf857605db5c52cfb9a90514d4f4a8f00280b43245115a23c27ff86ab322a43408e2e04d42d796034dcdd1b",
          "sha256": "26c713380a109782779ffe3d8501f831f6e82aa5af08bfee7a5f61fd1699135e",
          "sha1": "037255c3cc627defdeb87dc75a69827247ab56f0",
          "md5": "bd5a4522a3ebaf031a7bcd0c3796210d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-sources.jar",
          "url": "database-1.0.0-sources.jar",
          "size": 27138,
          "sha512": "66f6e8cec898724a829c224636afa8cc1c10580e0aa963782ea4fc1c53ec32b0007a25f2f86c7b7fa9be4387e65988bcf091dd95fc5f4a57ef15d2fe17b31f9a",
          "sha256": "dfcaac157e534ef291d8607bf4cb4037a52222c3acc188777b180351232ec0fe",
          "sha1": "09329ff3740aed1e07b52d4e47e9849599246891",
          "md5": "7c01208f10da42cb59c054c84c13637e"
        }
      ]
    }
  ]
}
