{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46264,
          "sha512": "7b77f753892bffd76da006f47582cfa34b71ba1f760d72ae90a4e2f33bf20aaa00ec11f3f4d8e3d329d43b542aa2f195337b51fa99e5eafb6dcc164c778dfd12",
          "sha256": "4af461bf263337f5d9157324bf20472d01d70a189f45463f04fdaaa78b7f06cb",
          "sha1": "14bf9c0ea700b54e9b160719eb3576ac5520eb5b",
          "md5": "7a9e6c731957fbbedd01162a6f3af6a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46264,
          "sha512": "7b77f753892bffd76da006f47582cfa34b71ba1f760d72ae90a4e2f33bf20aaa00ec11f3f4d8e3d329d43b542aa2f195337b51fa99e5eafb6dcc164c778dfd12",
          "sha256": "4af461bf263337f5d9157324bf20472d01d70a189f45463f04fdaaa78b7f06cb",
          "sha1": "14bf9c0ea700b54e9b160719eb3576ac5520eb5b",
          "md5": "7a9e6c731957fbbedd01162a6f3af6a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-javadoc.jar",
          "url": "database-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-sources.jar",
          "url": "database-1.0.0-sources.jar",
          "size": 27156,
          "sha512": "faa9dfc214aa5ec0e34e0e46279156dc28c683327bf24dcf6876d432e938672c0159d46fa880fa47795fc65ff61ac1134dee42e7ccbb23e309d19b51b2db5464",
          "sha256": "90af6d83c5260abc71eb9d94b4759b601f963e561d50895e589a0d3700055ec9",
          "sha1": "8e392e06b7fbef7750f85a834a82a132eb9340d2",
          "md5": "ad0791ac15f145727abf267939e7ede4"
        }
      ]
    }
  ]
}
