{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46250,
          "sha512": "32e4fd0a175cb4cd90aa484ac841195abdd1e917e08823871bcae0cce1e261e68ddc637af8c7f9aa88186eb9b96e3107ff6d915273ad376797736da2585ce451",
          "sha256": "bd56e7665e8995d1c415dde078a5a31071ea63f102720bb09a17cfd899ca3867",
          "sha1": "b27dac3c3c0335f2e38332b78c5cffac1a01443b",
          "md5": "daef8e517826c7ff9b14d4e4b0c5c8ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.32"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.0.4"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 46250,
          "sha512": "32e4fd0a175cb4cd90aa484ac841195abdd1e917e08823871bcae0cce1e261e68ddc637af8c7f9aa88186eb9b96e3107ff6d915273ad376797736da2585ce451",
          "sha256": "bd56e7665e8995d1c415dde078a5a31071ea63f102720bb09a17cfd899ca3867",
          "sha1": "b27dac3c3c0335f2e38332b78c5cffac1a01443b",
          "md5": "daef8e517826c7ff9b14d4e4b0c5c8ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-javadoc.jar",
          "url": "database-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-sources.jar",
          "url": "database-1.0.0-sources.jar",
          "size": 27138,
          "sha512": "d630480c29cebb91a9f6f8a278599add5018d86024ae84edae9e7b37f9d1dad0f6ea57bcf8d48dcabcb39f9677d6313a10d183aaf91e19132ff497b850839c8c",
          "sha256": "2f89963f1a93cf4718c984018282351bca0b0110011fc4cdf43f8acbb06aae8e",
          "sha1": "1f265fdd860813e2c95fd646608ef6f9356fac76",
          "md5": "e00aca060f6d48986d476c3bbe5f11cb"
        }
      ]
    }
  ]
}
