{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.1-beta-plain.jar",
          "url": "app-1.0.1-beta-plain.jar",
          "size": 6350,
          "sha512": "7f4b4f70ddcab75f04b2106df038436a8ab6d547d257ae215aec0075fff29b071e7384145cd7df41cd471eb54ca6afce9e344c89f68dedce8b8131c880b2a80e",
          "sha256": "2c4889bcd73f9fc3b40d2dac24dc7df5763ccee2c579b84775f8e55b006adfec",
          "sha1": "52b71902c7ab1be41065b8f24d7224a659b2e22c",
          "md5": "e0a7976f342d715fb4211a57cc4dbf77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.1-beta-plain.jar",
          "url": "app-1.0.1-beta-plain.jar",
          "size": 6350,
          "sha512": "7f4b4f70ddcab75f04b2106df038436a8ab6d547d257ae215aec0075fff29b071e7384145cd7df41cd471eb54ca6afce9e344c89f68dedce8b8131c880b2a80e",
          "sha256": "2c4889bcd73f9fc3b40d2dac24dc7df5763ccee2c579b84775f8e55b006adfec",
          "sha1": "52b71902c7ab1be41065b8f24d7224a659b2e22c",
          "md5": "e0a7976f342d715fb4211a57cc4dbf77"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.1-beta-javadoc.jar",
          "url": "app-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "ee9ca6185792b72005b262f5104418ee5ada7b0eb59d8cddad941bdc8daf739a616c458f3561767d7a5b4520e398866d43a6412f33c9c414b266f00076c1a31e",
          "sha256": "cf983342fb167aa7204663065ecd921ee5f490a674b931a956201535dff2374d",
          "sha1": "0239e0bc5c73012e3c282e9cf882a1957773ab3c",
          "md5": "97f5da75c13adaf60c49439c722dcc59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.1-beta-sources.jar",
          "url": "app-1.0.1-beta-sources.jar",
          "size": 5018,
          "sha512": "f60c8cc2d399e75d9805d4cdfc3e48e877044e9257e8787388cf5e14f66aabc2cf2f688464d0ab452c3a5b51fb0e0860fe736c8fb095abe3e39510fa01683d92",
          "sha256": "51c958c3f005c050ab73a26b0e61f92ea140143ac176d52347038b06ac7b8644",
          "sha1": "fc0b2b7728fde4f807ef8b36762c2fd1db4771c6",
          "md5": "0f2ce8665f5af3bc1c1d2760680d154f"
        }
      ]
    }
  ]
}
