{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "app",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.1-beta-plain.jar",
          "url": "app-1.0.1-beta-plain.jar",
          "size": 6075,
          "sha512": "b48bf494844983f7a0e2f38b90e12c7ac6026dfccd7b12008b904cf568a9d09415ff1a33541d294891d478f059cccc40533f0d882c661168f8e259042641f5c8",
          "sha256": "b6e3c9e3dce6e24f007dc1638bdc3bb423e1f7cfd9ebffb9932722d90338987f",
          "sha1": "1d3cfd6ecbbd245273c780ccfdd4e6afc5ce2908",
          "md5": "b5bd6c70270476b3bdfdedc5bc13ccfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "security",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.0.1-beta-plain.jar",
          "url": "app-1.0.1-beta-plain.jar",
          "size": 6075,
          "sha512": "b48bf494844983f7a0e2f38b90e12c7ac6026dfccd7b12008b904cf568a9d09415ff1a33541d294891d478f059cccc40533f0d882c661168f8e259042641f5c8",
          "sha256": "b6e3c9e3dce6e24f007dc1638bdc3bb423e1f7cfd9ebffb9932722d90338987f",
          "sha1": "1d3cfd6ecbbd245273c780ccfdd4e6afc5ce2908",
          "md5": "b5bd6c70270476b3bdfdedc5bc13ccfc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.1-beta-javadoc.jar",
          "url": "app-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "06096a774cabb840fa8dc581eeec21bda372c7df748ec42475ec8e758a0d31779c2cbea45d4818c33fdf6299736d6fa8424bfbe948606f3ffe80665371e01bc8",
          "sha256": "aceab66e5b204fabaa4dcc6ace432a339770c7142f69ed86246477162062f1bd",
          "sha1": "97cf48c0a8b89db3ad52e1e55b0c4adede61ccb5",
          "md5": "e23fb731ca9dbdb23ac4eefea4f81f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-1.0.1-beta-sources.jar",
          "url": "app-1.0.1-beta-sources.jar",
          "size": 4741,
          "sha512": "f912dc3b5ee39fd21f2604edc365c11be4dcd25b57d7275973ee2797f7b594a941b11b6005518056ccc7a3a44d6d34f8e54e2d6eac788f7e934404aca7ed0385",
          "sha256": "6391e7d56ac0fb160d9347dab24d11d9c29ec79c972742b3e92463c71335e824",
          "sha1": "7085e8456308ff379d474926eb88d8bcf9cdb92f",
          "md5": "3da3028dfbf4e0703091d694c3bc9a1a"
        }
      ]
    }
  ]
}
