{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "redis",
    "version": "1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.4-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.4-beta-plain.jar",
          "url": "redis-1.0.4-beta-plain.jar",
          "size": 6934,
          "sha512": "a950d5185b98333f11012cb95c612c9881902a9f5a3ac8471c5c66e911de21a8c377b2e83f2bc96bd1ddbdec07b35aa92892f63b856990a560432ce59b18c53d",
          "sha256": "82a2ec23deca74f63e80d1b5e26b3455ffef852768fe65fa4cce85fed8f4a014",
          "sha1": "a8220175e9d3c4bd588cc46db9e519de06ac1810",
          "md5": "c7b0d7046b5542902e5d1e3751277ee6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.4-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.session",
          "module": "spring-session-data-redis",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "redis-1.0.4-beta-plain.jar",
          "url": "redis-1.0.4-beta-plain.jar",
          "size": 6934,
          "sha512": "a950d5185b98333f11012cb95c612c9881902a9f5a3ac8471c5c66e911de21a8c377b2e83f2bc96bd1ddbdec07b35aa92892f63b856990a560432ce59b18c53d",
          "sha256": "82a2ec23deca74f63e80d1b5e26b3455ffef852768fe65fa4cce85fed8f4a014",
          "sha1": "a8220175e9d3c4bd588cc46db9e519de06ac1810",
          "md5": "c7b0d7046b5542902e5d1e3751277ee6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.4-beta-javadoc.jar",
          "url": "redis-1.0.4-beta-javadoc.jar",
          "size": 261,
          "sha512": "1bd776432ad1ce3e94786ea424cac3319902526d2713adc3801c7efae3c61983b8044cae12107e9dde8f8a21c0c9ff9f91466735cf203c0c93c46df790655474",
          "sha256": "5549ea18c4edf6371887988dbeebbdeb38c967620f0d2d16e55855911bc986c7",
          "sha1": "735bc3607590cd26c6974d5a5f0f461398e8140c",
          "md5": "041b8c13c5e3c25f1e8fddfc81a8b0bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "redis-1.0.4-beta-sources.jar",
          "url": "redis-1.0.4-beta-sources.jar",
          "size": 3644,
          "sha512": "92fa8a9eb7c727c9a0ca6562ab217f549a80f077fecf38c8d0437a5fdd26acdf71f5fe7cb8673c68288cb70a722ee0b4951b68939b927ab87cb606e9efd1f3e1",
          "sha256": "542d9e03338098bbb3ce20755397ee20f68da549baa8fc309ce36c9bb2984bee",
          "sha1": "43aaa77d330e50c8e061283eb0ce415aab823400",
          "md5": "4100854326e1b2f6d3a6b0b5dfdd984f"
        }
      ]
    }
  ]
}
