{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "route",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19383,
          "sha512": "8cea3b2ab921727955509ad9276f2939c9b83c07ca768aa28bc9f1038c22a1564eb7a5ab615cd140fcfec753dabd312fa94b9e3564f54a6b1c62323ccad77a1b",
          "sha256": "99b3778468d8e5abb0f0a6bc6c6f5056b81c54af8c4c2f59f84339ec67ac5948",
          "sha1": "86bbf3189529ce51d382ce726254fa6435e80fc8",
          "md5": "7b1f68d3059549d58c8062369a5267e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19383,
          "sha512": "8cea3b2ab921727955509ad9276f2939c9b83c07ca768aa28bc9f1038c22a1564eb7a5ab615cd140fcfec753dabd312fa94b9e3564f54a6b1c62323ccad77a1b",
          "sha256": "99b3778468d8e5abb0f0a6bc6c6f5056b81c54af8c4c2f59f84339ec67ac5948",
          "sha1": "86bbf3189529ce51d382ce726254fa6435e80fc8",
          "md5": "7b1f68d3059549d58c8062369a5267e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-javadoc.jar",
          "url": "route-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1c4a3782605b1561bfc05a539bee976f7b566f73c0298f0d7d4506e259233d4b8eb9522f5abe41e9d6c8ed1fa902ae13396e3de642d5da2484c61b5e70cdf2ae",
          "sha256": "6ec44dc1ac5b3d02373303793046a9e09fb1baed018329143004620edf7e9a58",
          "sha1": "305a6a63694ff047334636932c36d10dd7a608b4",
          "md5": "072d9f9a15500a95ac79ceeb78530908"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-sources.jar",
          "url": "route-1.0.0-sources.jar",
          "size": 13595,
          "sha512": "0dd4b304c0dee1ea9f9efe70c63a9edcac9438f4624bad9ce8a37a1355c8817ccbb9a67471946d7b17b8138830ceaa7e6764a5dc90c406197f6696cc810713ea",
          "sha256": "c60d23dabf312719b79205a7875ff9d0465e5a2b5c82dfd4f42154166e2acd6c",
          "sha1": "639b2ff5d355588665276ec32f3a3f2bc48cf6e1",
          "md5": "64d73508f0607c2d81f871d600fb9d9e"
        }
      ]
    }
  ]
}
