{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "route",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19381,
          "sha512": "a571aace23d6aa25761bc5237995b1e08bfbccb852c827771b8bf1ea8efb08d4e74ea4ce5ce70ae12f00c3ace1b30ca6d5c581b9a006bd9e52334eac5e25dcf5",
          "sha256": "79c4ef67a88f53ec0034bcbf8b4f1a7be435ac0441e03dfc0d637964ae2b94e8",
          "sha1": "eea69c1a7e70858bae7ccc1651dba55c8ff8b438",
          "md5": "bca14d844e3f6d30a13a05e05579a3a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19381,
          "sha512": "a571aace23d6aa25761bc5237995b1e08bfbccb852c827771b8bf1ea8efb08d4e74ea4ce5ce70ae12f00c3ace1b30ca6d5c581b9a006bd9e52334eac5e25dcf5",
          "sha256": "79c4ef67a88f53ec0034bcbf8b4f1a7be435ac0441e03dfc0d637964ae2b94e8",
          "sha1": "eea69c1a7e70858bae7ccc1651dba55c8ff8b438",
          "md5": "bca14d844e3f6d30a13a05e05579a3a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-javadoc.jar",
          "url": "route-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-sources.jar",
          "url": "route-1.0.0-sources.jar",
          "size": 13593,
          "sha512": "6e60650b612fceb77c4d1ba8f26d64088aa984712bb2cda2a945d79b7fa04c8ed9d6f437d49db33367bedd9698b578180868ecf699f1a83548c827117fe155c3",
          "sha256": "ee743db7a9fd4170e03fd5429a13bbaf1607c38c660004d326b77d142de96495",
          "sha1": "37f642950b006e50eb0c21ca597e816c1dd13888",
          "md5": "b23991eb34bed6b4ba9fb54f1ead0770"
        }
      ]
    }
  ]
}
