{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "route",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19383,
          "sha512": "6268ecf7015dbb5e83758afae72e3ef81bff64bea6e50d8229b0d14bc45151067aa873cb1581ad68da7b4037aea7434c374ac196a95bc2b8b2387d13241eb94d",
          "sha256": "42fb30ca06eb3882b022924d2185b6c0d6a2474880b6b0dbfc7714d054d7d2dc",
          "sha1": "e985bcc17d1b1c918050c376c7e84147fad50895",
          "md5": "6f537e559921fa351482c6aeb0e2b3c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "route-1.0.0-plain.jar",
          "url": "route-1.0.0-plain.jar",
          "size": 19383,
          "sha512": "6268ecf7015dbb5e83758afae72e3ef81bff64bea6e50d8229b0d14bc45151067aa873cb1581ad68da7b4037aea7434c374ac196a95bc2b8b2387d13241eb94d",
          "sha256": "42fb30ca06eb3882b022924d2185b6c0d6a2474880b6b0dbfc7714d054d7d2dc",
          "sha1": "e985bcc17d1b1c918050c376c7e84147fad50895",
          "md5": "6f537e559921fa351482c6aeb0e2b3c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-javadoc.jar",
          "url": "route-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "route-1.0.0-sources.jar",
          "url": "route-1.0.0-sources.jar",
          "size": 13595,
          "sha512": "8a8d9625a1f27f4a252a6cb982b9f88945aecf0fe7fb0ab1662fea34616bdb4a3871c0a2467a52fa616ab8c752ed756ea1257b45c86a56bcd6f3562b0f74d4da",
          "sha256": "cc0dd9e5d14a0bc7b62ee100baa88850eadb4b2c94cbc987cc2a316c332091a1",
          "sha1": "7f401bcf8468dbdc401b58288050cd5b5459273e",
          "md5": "a48a96be48df01850773a6fa618a8a6f"
        }
      ]
    }
  ]
}
