{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 2117,
          "sha512": "11b0af13b62f879b5f9665b1861da8b6b4a77b4b06c9bac0b47f7825bf536a3eb7646696e7f1fd6d8f899e19b9618d33f4a8d17ffebc10b6b1d8047a1526c9ce",
          "sha256": "40fa6ea79b6c4d349ed0fe9bf7967163eb7ac62b4686027a519f6a23416b925b",
          "sha1": "61873d87016aa466e25e601b88b9d8fb1856cc07",
          "md5": "372103ad3a778428ec7e3a90ea8b8ffb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.0.31"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "druid-spring-boot-starter",
          "version": {
            "requires": "1.2.16"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.mybatis.spring.boot",
          "module": "mybatis-spring-boot-starter",
          "version": {
            "requires": "3.0.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-boot-starter",
          "version": {
            "requires": "3.5.3.1"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.protobuf",
              "module": "protobuf-java"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-1.0.0-plain.jar",
          "url": "database-1.0.0-plain.jar",
          "size": 2117,
          "sha512": "11b0af13b62f879b5f9665b1861da8b6b4a77b4b06c9bac0b47f7825bf536a3eb7646696e7f1fd6d8f899e19b9618d33f4a8d17ffebc10b6b1d8047a1526c9ce",
          "sha256": "40fa6ea79b6c4d349ed0fe9bf7967163eb7ac62b4686027a519f6a23416b925b",
          "sha1": "61873d87016aa466e25e601b88b9d8fb1856cc07",
          "md5": "372103ad3a778428ec7e3a90ea8b8ffb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-javadoc.jar",
          "url": "database-1.0.0-javadoc.jar",
          "size": 109208,
          "sha512": "3dacbccd20f5c0fe86e7d03491b14d75aed3c3e445c7a07c6234f54175ab3b029bed1a2993993c036c664fa6d800122b7e563dbbe41205edb1c9aaacf449567d",
          "sha256": "a032d659d9332080c5224831b311aaee99e0bdb0e381811a16cbb32b8873513a",
          "sha1": "ea1d10ed059c49097cccb4ce931a6f3a79ffc55a",
          "md5": "3b5a372ab3e108823e731e4690b6e66e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-1.0.0-sources.jar",
          "url": "database-1.0.0-sources.jar",
          "size": 1931,
          "sha512": "0e127575df968d99956ba128824a2c2c6d11246b65506188baf9165209635666b9810dcc01baa687f0f5fe5ff1e537e5f9c7445f63d8eb33b060dfd083152d83",
          "sha256": "0d67963de65c4a2d3af891bc89e9c37b05e425b8b453da37314154449af05176",
          "sha1": "e576470fd53ea781b374d16ff8a143c13b3deb27",
          "md5": "0839406270a0d13ad1c2ae434bc2f3f2"
        }
      ]
    }
  ]
}
