{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.1-beta-plain.jar",
          "url": "operation-log-1.0.1-beta-plain.jar",
          "size": 41884,
          "sha512": "8020152dc91807637318f3196896f47d0a7b8ee4f880da921068ba46f2bb41dfbf0752c52216df0eb434cc74f4d99266f66ddcf5e260f7ac92fe01f246b7fbaf",
          "sha256": "c50f13848e89493179fe518e45cee2810aeda2936cfb33c3bf1d58c4b9fb1512",
          "sha1": "cb34a7648c56f8a4ce3a11c3c2f8634f952c09a5",
          "md5": "ff3bcc54a7a8f731d25b04ffa7511bce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.1-beta-plain.jar",
          "url": "operation-log-1.0.1-beta-plain.jar",
          "size": 41884,
          "sha512": "8020152dc91807637318f3196896f47d0a7b8ee4f880da921068ba46f2bb41dfbf0752c52216df0eb434cc74f4d99266f66ddcf5e260f7ac92fe01f246b7fbaf",
          "sha256": "c50f13848e89493179fe518e45cee2810aeda2936cfb33c3bf1d58c4b9fb1512",
          "sha1": "cb34a7648c56f8a4ce3a11c3c2f8634f952c09a5",
          "md5": "ff3bcc54a7a8f731d25b04ffa7511bce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.1-beta-javadoc.jar",
          "url": "operation-log-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "7ca640ef0cd1e493242ceb97ba0133bc687d68bd40dec7ca27eada9dceff15a68c6e58da574d14d5e069c05dec6003d68bab000f08437028926d5fc8404d6e26",
          "sha256": "df6df0939115a679dcfe2a018715f6116ebef6bb42987d3034c7f8227acf828c",
          "sha1": "14a607bd8c18c8021e01c47122a5dad0f163a762",
          "md5": "0f9ebeabb8c453d5be4c4c455341fdbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.1-beta-sources.jar",
          "url": "operation-log-1.0.1-beta-sources.jar",
          "size": 27810,
          "sha512": "a4ae1c968180468420d38a831a1114e22c9a1c95e96c38613630211f7c3e4edc11f4453addb731845716aaa3ed261578d7eca2f776c5f88c8a28753124079389",
          "sha256": "11443456400102099e8711bbb45f6b330054e8455a7f3043cd67233c5420ab46",
          "sha1": "2cea2c619da73b00f1ced1b0861caf497ebeb07c",
          "md5": "f4bf643a7d6b2b3207c0d4bac60d69a1"
        }
      ]
    }
  ]
}
