{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.1-beta-plain.jar",
          "url": "operation-log-1.0.1-beta-plain.jar",
          "size": 41904,
          "sha512": "acc87d33dfbccd743723ff01a39c92b991e1d1912d7ffcce3f8294e2c7eee8c888d8907de96222208d02664124dd989214f3059d052b340c4775d424fd0ad53d",
          "sha256": "13dca443f62a96306ccbbf132a37629d32e2d8fbacc0f8952259f0fca1079b75",
          "sha1": "07a4b298f2f84774fe966249769a97f7ba7a2ae5",
          "md5": "8d7338f6b738c5366927520dce48b86c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.1-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.1-beta-plain.jar",
          "url": "operation-log-1.0.1-beta-plain.jar",
          "size": 41904,
          "sha512": "acc87d33dfbccd743723ff01a39c92b991e1d1912d7ffcce3f8294e2c7eee8c888d8907de96222208d02664124dd989214f3059d052b340c4775d424fd0ad53d",
          "sha256": "13dca443f62a96306ccbbf132a37629d32e2d8fbacc0f8952259f0fca1079b75",
          "sha1": "07a4b298f2f84774fe966249769a97f7ba7a2ae5",
          "md5": "8d7338f6b738c5366927520dce48b86c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.1-beta-javadoc.jar",
          "url": "operation-log-1.0.1-beta-javadoc.jar",
          "size": 261,
          "sha512": "7ca640ef0cd1e493242ceb97ba0133bc687d68bd40dec7ca27eada9dceff15a68c6e58da574d14d5e069c05dec6003d68bab000f08437028926d5fc8404d6e26",
          "sha256": "df6df0939115a679dcfe2a018715f6116ebef6bb42987d3034c7f8227acf828c",
          "sha1": "14a607bd8c18c8021e01c47122a5dad0f163a762",
          "md5": "0f9ebeabb8c453d5be4c4c455341fdbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.1-beta-sources.jar",
          "url": "operation-log-1.0.1-beta-sources.jar",
          "size": 27826,
          "sha512": "f02ea623f57f4cf1e06b8c239b64c4dab07f4db34807bef713d8212fd33dd4ffff341ef4f0d01e96f3096d1f7a45e6fa5a7112256bb5181db59879f7f98f25c7",
          "sha256": "24ebc93ff36a860736434311efa1acf09565bb57610595f8b4e6544a535ad93d",
          "sha1": "fdfe64bb05fa0a90ca069142a54d45bbc9cee02b",
          "md5": "1e937972c2f9df96641b95eac8c417fc"
        }
      ]
    }
  ]
}
