{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "spring",
    "version": "1.0.3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.3-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.3-beta-plain.jar",
          "url": "spring-1.0.3-beta-plain.jar",
          "size": 42458,
          "sha512": "58bbd231c5250f7554b7f58e5591143b0c055914d557bf5b9c1c19b30fae74bd10c64aed759d53c48b9d277a149b1104835de40843eeca7db7eabfd559176660",
          "sha256": "9bcad4249dbb9c94081ec225cc86a6f62d5de02fcacdf87bcfc370b53872e14b",
          "sha1": "3b0d80ac23e6f1a8e5b7f342ce221a2caa9fce93",
          "md5": "f9d3749ef42d6e826b538fdc45f042ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "common",
          "version": {
            "requires": "1.0.3-beta"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-1.0.3-beta-plain.jar",
          "url": "spring-1.0.3-beta-plain.jar",
          "size": 42458,
          "sha512": "58bbd231c5250f7554b7f58e5591143b0c055914d557bf5b9c1c19b30fae74bd10c64aed759d53c48b9d277a149b1104835de40843eeca7db7eabfd559176660",
          "sha256": "9bcad4249dbb9c94081ec225cc86a6f62d5de02fcacdf87bcfc370b53872e14b",
          "sha1": "3b0d80ac23e6f1a8e5b7f342ce221a2caa9fce93",
          "md5": "f9d3749ef42d6e826b538fdc45f042ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.3-beta-javadoc.jar",
          "url": "spring-1.0.3-beta-javadoc.jar",
          "size": 261,
          "sha512": "f84b7aa2fefa01337f27077c2749c64851b4523dc8b28c15fc0c064961700c411349b8f102175983e9249f927cc70c3d2750d2151738a0cc2c3ea3304c523bf1",
          "sha256": "9a8fbdd736d5bd2eccc7464923c24e4e592c1f3a9efea96a7f174054e5e0e5c4",
          "sha1": "ecb0f589ba9e80cda55048bb888144793c5fc6a4",
          "md5": "99145cad10b3c1734f5f9fc0cc49a0b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-1.0.3-beta-sources.jar",
          "url": "spring-1.0.3-beta-sources.jar",
          "size": 27565,
          "sha512": "48afeec6ca8cabf9dea4c6d8543c22a83e98afc97a36ecee835143baf3bba0e9652860eba26e507051ac225ccedf5ae54470dc55f24f22f35bac6ef884b5b986",
          "sha256": "9ea6fc76f82c6599be14046a864a12ea639ad057874a0d5c7f759e206fde9402",
          "sha1": "733d58f537071cc88fdf481fae3ea0a01b5c0b41",
          "md5": "beb6b22fcab625a7fd8e1909eac98c59"
        }
      ]
    }
  ]
}
