{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "operation-log",
    "version": "1.0.4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.4-beta-plain.jar",
          "url": "operation-log-1.0.4-beta-plain.jar",
          "size": 41865,
          "sha512": "bbce0a5cb692ce8f018726b665641d44cede55b4291cb8f1ca7286ccdafb1eada25ce76990ae9e69a63677b41931bd641cd3dd8fd79c8da882e4a938a5a32203",
          "sha256": "cbaaf1cc1a85f04dce6caf7eae70e243df8ba350125985968fd681b79adcce6d",
          "sha1": "7b5e4bd7dc57f62766c6c0762ebe571373fe4288",
          "md5": "e3a1e834f83e07fbd6dff995e44bb3f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.4-beta"
          }
        }
      ],
      "files": [
        {
          "name": "operation-log-1.0.4-beta-plain.jar",
          "url": "operation-log-1.0.4-beta-plain.jar",
          "size": 41865,
          "sha512": "bbce0a5cb692ce8f018726b665641d44cede55b4291cb8f1ca7286ccdafb1eada25ce76990ae9e69a63677b41931bd641cd3dd8fd79c8da882e4a938a5a32203",
          "sha256": "cbaaf1cc1a85f04dce6caf7eae70e243df8ba350125985968fd681b79adcce6d",
          "sha1": "7b5e4bd7dc57f62766c6c0762ebe571373fe4288",
          "md5": "e3a1e834f83e07fbd6dff995e44bb3f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.4-beta-javadoc.jar",
          "url": "operation-log-1.0.4-beta-javadoc.jar",
          "size": 261,
          "sha512": "1bd776432ad1ce3e94786ea424cac3319902526d2713adc3801c7efae3c61983b8044cae12107e9dde8f8a21c0c9ff9f91466735cf203c0c93c46df790655474",
          "sha256": "5549ea18c4edf6371887988dbeebbdeb38c967620f0d2d16e55855911bc986c7",
          "sha1": "735bc3607590cd26c6974d5a5f0f461398e8140c",
          "md5": "041b8c13c5e3c25f1e8fddfc81a8b0bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "operation-log-1.0.4-beta-sources.jar",
          "url": "operation-log-1.0.4-beta-sources.jar",
          "size": 27811,
          "sha512": "76d7f963813c71ef5dfd840b8f1acf5147c8ae0196c095cab1fa101fd2968ca0dd7cc7894612c8ea2c51d011769e22b257e7fa95ee421e02a630a8c3c090bdd1",
          "sha256": "6f8352e848a3b4b7033af67d3e97429100ee9f2961c332ee9f385a03d06e5d83",
          "sha1": "1690679e870e33d82444db0563d21f5094aec915",
          "md5": "dc3e5c14b1dc74050bf1f69a04541a99"
        }
      ]
    }
  ]
}
