{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 135213,
          "sha512": "22f3d88ff6ea54cbb24875c398b185ad601d0d2ed8aff704c0d3d098d84ce7412b430e15a775ce82e0e4e84a6056f4821f227bacdf218c0e37cc9677eee163f5",
          "sha256": "70d2f2f596166b22f1f63b95ce0d94b9f3adcab09eaf30142d693ebb38399737",
          "sha1": "89f9b1273d870f136d833827c0a447cc9039fe53",
          "md5": "b440d97757ba5ccfe1e4891ad1951959"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 135213,
          "sha512": "22f3d88ff6ea54cbb24875c398b185ad601d0d2ed8aff704c0d3d098d84ce7412b430e15a775ce82e0e4e84a6056f4821f227bacdf218c0e37cc9677eee163f5",
          "sha256": "70d2f2f596166b22f1f63b95ce0d94b9f3adcab09eaf30142d693ebb38399737",
          "sha1": "89f9b1273d870f136d833827c0a447cc9039fe53",
          "md5": "b440d97757ba5ccfe1e4891ad1951959"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-javadoc.jar",
          "url": "security-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7b7a3be588d898d29f4135ed7b5981279a0b518b17d92f313a5369367561c70f95e666c2e91b9aa361a4cc625a928fb8c6ae5d3e45383db794aa2e092532b69e",
          "sha256": "ad56729b478af841239e575baade443b9ba419320284afe291ab521a279646db",
          "sha1": "851cdeea6617510a3445358fb3f187b11cab83c6",
          "md5": "542397d5212f45a776bc298ee54e7f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-sources.jar",
          "url": "security-1.0.0-sources.jar",
          "size": 85662,
          "sha512": "a173877d184655ee33925e96098635d76b165420028e4549e656a7a58d36fa2e8c3bcf2b1a6fd21d8b2329f4d4e60c4319d2b6e647ad209e5888b2a44049523c",
          "sha256": "4f82c5e4c315d833e38fd6442aec0309a14ce53860ed189e61d9bbc8a54d915b",
          "sha1": "4447a719c5ede0f3c7c24a1aac8a81e6b36da3c3",
          "md5": "659e1e929873b25332bfcc40910d4e7e"
        }
      ]
    }
  ]
}
