{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 135264,
          "sha512": "4b08df6f173d750a9d099626470fdcb78981bb1017fef31174ca0e355ef776f24f1faf325b010897b9b68c83c8d3145cb22b0e4bea91f3630650f733b6e90499",
          "sha256": "0003ae9d21e956c94314cf2e3ab690bb6a9407f10eb20b33267e486a5333f685",
          "sha1": "c747360b4e9e885d877585ce5283b22f9c7ad269",
          "md5": "3cafd8767acd52159d63f9cf6fdb4623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 135264,
          "sha512": "4b08df6f173d750a9d099626470fdcb78981bb1017fef31174ca0e355ef776f24f1faf325b010897b9b68c83c8d3145cb22b0e4bea91f3630650f733b6e90499",
          "sha256": "0003ae9d21e956c94314cf2e3ab690bb6a9407f10eb20b33267e486a5333f685",
          "sha1": "c747360b4e9e885d877585ce5283b22f9c7ad269",
          "md5": "3cafd8767acd52159d63f9cf6fdb4623"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-javadoc.jar",
          "url": "security-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "7b7a3be588d898d29f4135ed7b5981279a0b518b17d92f313a5369367561c70f95e666c2e91b9aa361a4cc625a928fb8c6ae5d3e45383db794aa2e092532b69e",
          "sha256": "ad56729b478af841239e575baade443b9ba419320284afe291ab521a279646db",
          "sha1": "851cdeea6617510a3445358fb3f187b11cab83c6",
          "md5": "542397d5212f45a776bc298ee54e7f34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-sources.jar",
          "url": "security-1.0.0-sources.jar",
          "size": 85703,
          "sha512": "eac0199d2ea6317509d0e2efebf25c4792d23127e482a846d2c055194dd03455ed112121e312b3a8ba87ed075959ad7e99d22e04ba5f0134f994a08e0cd9d6e0",
          "sha256": "811c95a006bca67156561a5cc0f5646252f756c8df365eff1f75cb3958baee50",
          "sha1": "e8deeeb8a33ec328c0e2b7e7dcae87ffaa429bb9",
          "md5": "bd58367809b24cd6bf914a9e6c70bdda"
        }
      ]
    }
  ]
}
