{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "security",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 134756,
          "sha512": "3eda366ec2890fe5daf802af083fc15ebd4dfd3faf1c47074c3be823777914a3f62ca31f0cf26f457a1075e1fef458f66c287ca5fa710b24c1b8575fc0553a10",
          "sha256": "dd87767e66eebd8cddf7e8581178641df1f8b759da6d9c17f4049edde4c1f1bb",
          "sha1": "5b8ee19eaa96c9d57f4b471b445fbace1f979a71",
          "md5": "f0160bdb9cef92ee0a351060bd43b22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.whvcse",
          "module": "easy-captcha",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.4"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "spring",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "database-backup",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "route",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "security-1.0.0-plain.jar",
          "url": "security-1.0.0-plain.jar",
          "size": 134756,
          "sha512": "3eda366ec2890fe5daf802af083fc15ebd4dfd3faf1c47074c3be823777914a3f62ca31f0cf26f457a1075e1fef458f66c287ca5fa710b24c1b8575fc0553a10",
          "sha256": "dd87767e66eebd8cddf7e8581178641df1f8b759da6d9c17f4049edde4c1f1bb",
          "sha1": "5b8ee19eaa96c9d57f4b471b445fbace1f979a71",
          "md5": "f0160bdb9cef92ee0a351060bd43b22d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-javadoc.jar",
          "url": "security-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "1c4a3782605b1561bfc05a539bee976f7b566f73c0298f0d7d4506e259233d4b8eb9522f5abe41e9d6c8ed1fa902ae13396e3de642d5da2484c61b5e70cdf2ae",
          "sha256": "6ec44dc1ac5b3d02373303793046a9e09fb1baed018329143004620edf7e9a58",
          "sha1": "305a6a63694ff047334636932c36d10dd7a608b4",
          "md5": "072d9f9a15500a95ac79ceeb78530908"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "security-1.0.0-sources.jar",
          "url": "security-1.0.0-sources.jar",
          "size": 85138,
          "sha512": "4beb7bb4bf7dcfa4bd2a0f5cf392aae9736d5c4c9ffa56ff7260ea0623cadbdaf3614f43be8a736d20af273339198408489eb4e79d128cb938cf1e1c467b42d1",
          "sha256": "af3a6bd3e0538954e36ac0f64a9f8000da71850b6f7cd2d3ccb39e790f82321e",
          "sha1": "3690cc1edff8ebb5faa741a8a002f48dc163a46c",
          "md5": "82b9f2c08c3f2113e8fb12ff3a75957a"
        }
      ]
    }
  ]
}
