{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.0-plain.jar",
          "url": "database-backup-1.0.0-plain.jar",
          "size": 22547,
          "sha512": "f8c82febfe170cac9be2b5122ac73aa56c58d21b3455ff8bdbff10fbcf5903984ba46b6ad7cec672a983f06b82a8090a0ead7b8f256102107cab9d73a3dd7bcc",
          "sha256": "6bb6b13832e34fa6c1c7532e65dd7b917e1b946bf56a3f611129e9de4ccfa95c",
          "sha1": "78ff2bd40f47db4705dcae6dc509ff97801a406c",
          "md5": "a06aa7e4e59f4c6439f6ecdd98d9129c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.0-plain.jar",
          "url": "database-backup-1.0.0-plain.jar",
          "size": 22547,
          "sha512": "f8c82febfe170cac9be2b5122ac73aa56c58d21b3455ff8bdbff10fbcf5903984ba46b6ad7cec672a983f06b82a8090a0ead7b8f256102107cab9d73a3dd7bcc",
          "sha256": "6bb6b13832e34fa6c1c7532e65dd7b917e1b946bf56a3f611129e9de4ccfa95c",
          "sha1": "78ff2bd40f47db4705dcae6dc509ff97801a406c",
          "md5": "a06aa7e4e59f4c6439f6ecdd98d9129c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.0-javadoc.jar",
          "url": "database-backup-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.0-sources.jar",
          "url": "database-backup-1.0.0-sources.jar",
          "size": 14665,
          "sha512": "ebeab3ba5e7cbbb73713131d500cac8328927ac18438ea4af0ae93a51f3288fb3774eac3cbe8e7a389e4216a6d2e3b1101a651f8967d8f40c352a77e70d12fd9",
          "sha256": "0c8e61e2cf07489ab028ef33599365cdc97137db0b4e201914d166787707483c",
          "sha1": "82fbaa9d4a02a9f9c7b00f6ac3ef8fbd1e3d2912",
          "md5": "c0e79c85c4e22ad4dbf2bee83ab9f206"
        }
      ]
    }
  ]
}
