{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "database-backup",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.0-plain.jar",
          "url": "database-backup-1.0.0-plain.jar",
          "size": 22541,
          "sha512": "6a69729144bfb110de11c81c60c89d27810bf0c73a6a1cf268ceae6d988d199595255bf89242d97e527fb949debf7a5f0103d09c81f7007d45d61b60bc107316",
          "sha256": "1894a921869746454a4283f19f2320338b03fefe23b050676ffd642bc8688a65",
          "sha1": "52cd0ee9fa49c03c1e9a4d604e0f2ab3697cfc2b",
          "md5": "d0491a70084988bc077f4ec4966a0e2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "database",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.gin.framework",
          "module": "operation-log",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "database-backup-1.0.0-plain.jar",
          "url": "database-backup-1.0.0-plain.jar",
          "size": 22541,
          "sha512": "6a69729144bfb110de11c81c60c89d27810bf0c73a6a1cf268ceae6d988d199595255bf89242d97e527fb949debf7a5f0103d09c81f7007d45d61b60bc107316",
          "sha256": "1894a921869746454a4283f19f2320338b03fefe23b050676ffd642bc8688a65",
          "sha1": "52cd0ee9fa49c03c1e9a4d604e0f2ab3697cfc2b",
          "md5": "d0491a70084988bc077f4ec4966a0e2b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.0-javadoc.jar",
          "url": "database-backup-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ed2d361ede710efdcdc556d5fd3ed0887e7221fff80c20dc405f1461941ae218123a3e5049b0a4200d197f6c629c2a064a4741aa0a4544c296e5f1b3c4e4615b",
          "sha256": "b5d7a35dded976fc2693be5ded64b28ee1fe329dbe5a148a8aa916a137cb5614",
          "sha1": "01c5299671348f98b0c439caa31795654d2d4c1e",
          "md5": "c0b3e42b35fd407f9cc57185e7411c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "database-backup-1.0.0-sources.jar",
          "url": "database-backup-1.0.0-sources.jar",
          "size": 14663,
          "sha512": "6cfa217a7356efe5badf9d94ecb874286a048ee0f61558e115af24cfc87ad0b0132fa6720b32e979774c9380f7d52fb8ae4095cb4e6b3558f993edaf4223c010",
          "sha256": "e5fc7df56e4268bf06cea3946dfde2522a66cc5cc47824cbef30120f79b79cc6",
          "sha1": "7ee44fb850d502bc65a1d5bfbfcf55b94b169055",
          "md5": "c3bd064184995364831a50a6bddd6481"
        }
      ]
    }
  ]
}
