{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 47734,
          "sha512": "dbd0d600cd329256cfc2754698ca140cd66cebf35efd02169efc86f18a4ad57dfa35d4c1ce4228d8806f8aae58633c3518551cd89c13eaa6ad2853d74d77ba13",
          "sha256": "6d5794b4d02804ba88e662dfa62f0f4d9bcf604412b4852a3193b890448caf4e",
          "sha1": "ff66ad2046b27c0924c6e91d5380bef4f19628f6",
          "md5": "4539605618a54472b5681e1cdf2707f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 47734,
          "sha512": "dbd0d600cd329256cfc2754698ca140cd66cebf35efd02169efc86f18a4ad57dfa35d4c1ce4228d8806f8aae58633c3518551cd89c13eaa6ad2853d74d77ba13",
          "sha256": "6d5794b4d02804ba88e662dfa62f0f4d9bcf604412b4852a3193b890448caf4e",
          "sha1": "ff66ad2046b27c0924c6e91d5380bef4f19628f6",
          "md5": "4539605618a54472b5681e1cdf2707f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-javadoc.jar",
          "url": "common-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-sources.jar",
          "url": "common-1.0.0-sources.jar",
          "size": 26903,
          "sha512": "f9342de7ed3b88c5257777d123272c0ea9d6754b3ccd7945eac3d84adb0800689f6f40258170663f1ec7cffa6e5fc527f3d4c0cbca53587d3f92b3825cd60b29",
          "sha256": "ca2752b540e4b19b3c860a6343028e4433f0ee5a379783ffb61aefaf03f9c0c5",
          "sha1": "09abf470fb47eaab4a86e631dc8003eebe6475e4",
          "md5": "f1427b46092ff845a6796fa509df126e"
        }
      ]
    }
  ]
}
