{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 48049,
          "sha512": "b724c1974193ef5ec55c9a0c98638418da1ef24afbe92fe6ef8ca5edb9631b2fdcc12e569914fb7e130449f45f2168827f22f31f601be564442087c2f88f3988",
          "sha256": "2a0299a918545a8c3fb9d104a2163253749319d70da7235dd32cff039a307237",
          "sha1": "1265e4bd53a21c7f1f541af17973141a1f3ca05e",
          "md5": "63a7db556fd0537ab1afca4633a49f63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-starter-webmvc-ui",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.xiaoymin",
          "module": "knife4j-springdoc-ui",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 48049,
          "sha512": "b724c1974193ef5ec55c9a0c98638418da1ef24afbe92fe6ef8ca5edb9631b2fdcc12e569914fb7e130449f45f2168827f22f31f601be564442087c2f88f3988",
          "sha256": "2a0299a918545a8c3fb9d104a2163253749319d70da7235dd32cff039a307237",
          "sha1": "1265e4bd53a21c7f1f541af17973141a1f3ca05e",
          "md5": "63a7db556fd0537ab1afca4633a49f63"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-javadoc.jar",
          "url": "common-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-sources.jar",
          "url": "common-1.0.0-sources.jar",
          "size": 27087,
          "sha512": "7dae6effb0f8d7f7c126034b92c6ee166fcc48be32540468a2f740f74b22639e95dd92b4dcd3c106b024369b7770a590d0e153fd02381df23bbe630446b00b37",
          "sha256": "16c8984f1c1c47b278dbaa498c5107789d9dc7b8be8f87401a57386d53c76096",
          "sha1": "5ade2282b7d14cb20ec822a7fac79f5ffa312ecd",
          "md5": "b0172b0d1fe076c67d5e5a9b2226e2c4"
        }
      ]
    }
  ]
}
