{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gin.framework",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 39229,
          "sha512": "7f5a4654bdc6a68e7c7b06a4fd1ba2b5a6b4e2419d5af2df088954e48db1b4f0a19b9c307da2600d7c49c23de26fc15174b4bfc2ea72f6ad619dceac16d2cedc",
          "sha256": "fe10c60e8670ba16a9118b45ee7fd56c19ca3f321f649219df9bf08fe86a0121",
          "sha1": "8de12660057a9d80f44e612b86eb4ab6dba5e622",
          "md5": "a260d25816c3bbcfc4c68c6d074ae1fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gin.framework",
          "module": "jackson",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0-plain.jar",
          "url": "common-1.0.0-plain.jar",
          "size": 39229,
          "sha512": "7f5a4654bdc6a68e7c7b06a4fd1ba2b5a6b4e2419d5af2df088954e48db1b4f0a19b9c307da2600d7c49c23de26fc15174b4bfc2ea72f6ad619dceac16d2cedc",
          "sha256": "fe10c60e8670ba16a9118b45ee7fd56c19ca3f321f649219df9bf08fe86a0121",
          "sha1": "8de12660057a9d80f44e612b86eb4ab6dba5e622",
          "md5": "a260d25816c3bbcfc4c68c6d074ae1fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-javadoc.jar",
          "url": "common-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "84dc5dcae22d60a22e946d267d3f53070d093e9866b0bc91e4e260349a795d73ec1a67957a1e5bdeb2d80c0af5ffeebf34b8c2f7d638169a02c11fc721e49ae2",
          "sha256": "2b227e5111fb188357013a171096314acc72cfe93822dc20b0bf6c9e5e55f8b3",
          "sha1": "782c5d688260a4eacf0a2b92b41c216f967954e1",
          "md5": "aa223e32f9fa65cedf8205fcf4f275ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.0-sources.jar",
          "url": "common-1.0.0-sources.jar",
          "size": 22549,
          "sha512": "91b0e3863b702a5c416fface1ce45e274e50933ec345616425cbdaa66b5d342a1594b1adafd144f0c8f57eff99b4cb49bd45fc94ba0ce77e80a916cde15ac099",
          "sha256": "6727ea768e5bd7d4e9f45e013d098b4857fafe1d564fe4b80d5a5cd2efee3529",
          "sha1": "0f01846943eac0dfe7c4e8f47b27a4bc0010d847",
          "md5": "b41bc4ad01745bad76126b8baf4eecb7"
        }
      ]
    }
  ]
}
